// Multi-Language Support for JAN-ASSIST
// Languages: English (en), Tamil (ta), Hindi (hi), Telugu (te), Malayalam (ml), Kannada (kn)

const translations = {
    en: {
        // Navbar
        navHome: "Home",
        navAbout: "About",
        navEligibility: "Check Eligibility",
        navSchemes: "Schemes",
        getStarted: "Get Started",

        // Index page
        badge: "⭐ Trusted by 12 Lakh+ Citizens",
        title: '<span class="white-text">Government Support,</span><br><span class="gradient-text">Made Simple</span>',
        sub: "Check your eligibility for 350+ central & state government schemes in just 2 minutes. Free, fast, and completely secure.",
        search: "Search",
        stat1: "Schemes Available",
        stat2: "Citizens Helped",
        stat3: "States Covered",
        categoryTitle: "Browse by Category",
        categorySub: "Find schemes tailored to your needs across various government departments",
        cat1: "Education",
        cat2: "Agriculture",
        cat3: "Women Empowerment",
        cat4: "Senior Citizens",
        cat5: "Healthcare",
        cat6: "Housing",
        cat7: "Child Welfare",
        cat8: "Employment",
        cat1_desc: "45 schemes",
        cat2_desc: "38 schemes",
        cat3_desc: "32 schemes",
        cat4_desc: "28 schemes",
        cat5_desc: "40 schemes",
        cat6_desc: "25 schemes",
        cat7_desc: "20 schemes",
        cat8_desc: "35 schemes",

        // About page
        aboutStory: "Our Story",
        aboutTitle: 'About<br><span class="grad-text">JAN-ASSIST</span>',
        aboutDesc: "India's most trusted government scheme eligibility platform — empowering 12 lakh+ citizens to discover, understand, and access the welfare programs they truly deserve.",
        aboutCheck: "Check Eligibility",
        aboutBrowse: "Browse Schemes",
        aboutScroll: "Scroll to explore",
        aboutStat1: "Government Schemes",
        aboutStat2: "Citizens Supported",
        aboutStat3: "States Covered",
        aboutStat4: "Secure Platform",
        aboutOffer: "What We Offer",
        aboutOfferTitle: 'Built Around <span class="grad-text">You</span>',
        aboutOfferSub: "Every feature is designed to remove friction and put the right information in your hands instantly.",
        aboutPurposeTitle: "Our Purpose",
        aboutPurposeBody: "JAN-ASSIST bridges the gap between citizens and government welfare programs. Millions of eligible citizens remain unaware of the benefits they deserve — we exist to change that. Our platform simplifies discovery based on your personal profile.",
        aboutPurposeTag: "Core Purpose",
        aboutMissionTitle: "Our Mission",
        aboutMissionBody: "To make government scheme discovery effortless for every Indian citizen, regardless of education level, language, or location. We believe every rupee earmarked for welfare should reach those who need it most.",
        aboutMissionTag: "Mission Driven",
        aboutBenefitsTitle: "Key Benefits",
        aboutBenefitsBody: "Check eligibility from home — no queues, no paperwork, no confusion. Our instant matching engine uses official criteria to surface the most relevant schemes for your age, income, occupation, state, and category.",
        aboutBenefitsTag: "Free Forever",
        aboutTransTitle: "Full Transparency",
        aboutTransBody: "We display clear, complete eligibility criteria for every scheme — directly from official government sources. No hidden steps. No paywalls. No misleading summaries. What you see is exactly what is required.",
        aboutTransTag: "Open Source Data",
        aboutAccessTitle: "Accessibility First",
        aboutAccessBody: "Available in 6 regional languages — English, Tamil, Hindi, Malayalam, Telugu, and Kannada. Designed to work on any device, any screen size, and even on slow internet connections across rural India.",
        aboutAccessTag: "6 Languages",
        aboutGovtTitle: "Scheme Support",
        aboutGovtBody: "From PM-KISAN to Beti Bachao Beti Padhao — we cover 350+ central and state government schemes across education, agriculture, healthcare, housing, women welfare, and more. Every scheme links to its official government portal.",
        aboutGovtTag: "350+ Schemes",
        aboutQuote: "Every citizen of India deserves to know about and access every welfare scheme they are entitled to. JAN-ASSIST exists to make that a reality — one eligibility check at a time.",
        aboutCite: "— The JAN-ASSIST Team",
        aboutValuesTag: "Our Values",
        aboutValuesTitle: "What We Stand For",
        aboutV1: "Citizen First",
        aboutV2: "Data Privacy",
        aboutV3: "Speed & Accuracy",
        aboutV4: "Free & Open",
        aboutV5: "Multi-Language",
        aboutV6: "Inclusive Design",
        aboutV7: "100% Secure",
        aboutV8: "Government Verified",
        aboutV9: "Mobile Friendly",
        aboutV10: "Always Updated",
        aboutCtaTitle: "Ready to Get Started?",
        aboutCtaDesc: "Join over 12 lakh citizens who have already discovered their government benefits. It takes less than 2 minutes — and it's completely free.",
        aboutCtaBtn: "Check My Eligibility",
        aboutFooter: "© 2026 JAN-ASSIST · Government Support, Made Simple",

        // Eligibility page
        eligEyebrow: "Citizen Services Portal",
        eligTitle: "Check Your Eligibility",
        eligSub: "Answer a few questions and our system will match you with every government welfare scheme you qualify for — instantly.",
        eligStep1: "Profile",
        eligStep2: "Details",
        eligStep3: "Results",
        eligSecA: "Personal Profile",
        eligSecB: "Economic & Social Details",
        eligName: "Full Name",
        eligNamePlaceholder: "e.g. Gugan",
        eligNameInvalid: "Please enter your full name (min 3 characters)",
        eligAge: "Age",
        eligAgePlaceholder: "18–100",
        eligAgeInvalid: "Enter valid age (1–120)",
        eligGender: "Gender",
        eligGenderSelect: "Select",
        eligGenderMale: "Male",
        eligGenderFemale: "Female",
        eligGenderOther: "Other",
        eligGenderInvalid: "Please select gender",
        eligState: "State / UT",
        eligStateSelect: "Select your state",
        eligStateInvalid: "Please select your state",
        eligOccupation: "Occupation",
        eligOccSelect: "Select occupation",
        eligOccFarmer: "Farmer / Agricultural Worker",
        eligOccSenior: "Senior Citizen",
        eligOccStudent: "Student",
        eligOccUnemployed: "Unemployed",
        eligOccHomemaker: "Homemaker",
        eligOccRetired: "Retired",
        eligOccInvalid: "Please select your occupation",
        eligIncome: "Annual Household Income",
        eligIncomeSub: "Annual Household Income",
        eligCategory: "Social Category",
        eligCatSelect: "Select category",
        eligCatGeneral: "General",
        eligCatObc: "OBC (Other Backward Class)",
        eligCatSc: "SC (Scheduled Caste)",
        eligCatSt: "ST (Scheduled Tribe)",
        eligCatEws: "EWS (Economically Weaker Section)",
        eligCatMinority: "Minority Community",
        eligCatInvalid: "Please select your category",
        eligContact: "Contact Number",
        eligContactPlaceholder: "Enter mobile number",
        eligDataLoc: "Your data is processed locally and never stored.",
        eligScanBtn: "Scan Eligibility",
        eligResTitle: "Eligibility Results",
        eligResMeta: "Loading…",
        eligStatMatched: "Schemes Matched",
        eligStatTopScore: "Top Match",
        eligStatBenefit: "Potential Benefit",
        eligSearchPlaceholder: "Filter schemes by name or ministry…",
        eligResNoMatch: "No schemes match your search. Try different keywords.",
        eligRecheck: "Re-check with New Profile",
        eligFooter: "© 2026 JAN-ASSIST · Government Support, Made Simple",

        // Schemes page
        schBadge: "Discover Your Benefits Instantly",
        schTitle: 'Explore Government<br><span class="gradient-text">Schemes</span>',
        schSub: "Navigate through India's most comprehensive database of government welfare schemes. Search, filter, and find the perfect scheme tailored to your needs — all in one place.",
        schStatTotal: "Total Schemes",
        schStatCat: "Categories",
        schStatFree: "Free Access",
        schSearchBtn: "Search",
        schSearchPlaceholder: "Search schemes by name, category, or description...",
        schFilters: "Filters:",
        schCatAll: "All Categories",
        schCatEdu: "Education",
        schCatHealth: "Healthcare",
        schCatAgri: "Agriculture",
        schCatWomen: "Women Welfare",
        schCatSenior: "Senior Citizens",
        schCatEmp: "Employment",
        schCatHousing: "Housing",
        schCatChild: "Child Welfare",
        schChipAll: "All",
        schChipEdu: "Education",
        schChipHealth: "Health",
        schChipAgri: "Agri",
        schChipWomen: "Women",
        schChipJobs: "Jobs",
        schResultsCount: "Showing schemes",
        schModalEligTitle: "Eligibility Criteria",
        schModalBtn: "Visit Official Site",
        schFooter: "© 2026 JAN-ASSIST. Built for the people of India.",

        // Shared dynamic text (cards, details, copy)
        cardTopMatch: "Top Match",
        cardEligible: "Eligible",
        cardEligMatch: "Eligibility Match",
        cardOfficialSite: "Official Site",
        cardVisitSite: "Visit Site",
        cardViewDetails: "View Details",
        cardEligibilityLabel: "Eligibility:",
        cardNoSchemesFound: "No Schemes Found",
        cardNoSchemesSub: "Try adjusting your search terms or filter criteria.",
        cardShowingSchemes: "Showing <span>{count}</span> scheme{plural}"
    },
    ta: {
        // Navbar
        navHome: "முகப்பு",
        navAbout: "பற்றி",
        navEligibility: "தகுதி சரிபார்க்க",
        navSchemes: "திட்டங்கள்",
        getStarted: "தொடங்கவும்",

        // Index page
        badge: "⭐ 12 லட்சம் குடிமக்களின் நம்பிக்கை",
        title: '<span class="white-text">அரசு உதவி,</span><br><span class="gradient-text">எளிமையாக்கப்பட்டது</span>',
        sub: "350+ மத்திய மற்றும் மாநில அரசுத் திட்டங்களுக்கு உங்கள் தகுதியை வெறும் 2 நிமிடங்களில் சரிபார்க்கவும். இலவசம், வேகமானது மற்றும் முற்றிலும் பாதுகாப்பானது.",
        search: "தேடுக",
        stat1: "கிடைக்கும் திட்டங்கள்",
        stat2: "உதவி பெற்ற குடிமக்கள்",
        stat3: "உள்ளடக்கிய மாநிலங்கள்",
        categoryTitle: "பிரிவு வாரியாக தேடுக",
        categorySub: "பல்வேறு அரசுத் துறைகளில் உங்கள் தேவைகளுக்கு ஏற்ப வடிவமைக்கப்பட்ட திட்டங்களைக் கண்டறியவும்",
        cat1: "கல்வி",
        cat2: "விவசாயம்",
        cat3: "பெண்கள் முன்னேற்றம்",
        cat4: "மூத்த குடிமக்கள்",
        cat5: "சுகாதாரம்",
        cat6: "வீட்டுவசதி",
        cat7: "குழந்தைகள் நலன்",
        cat8: "வேலைவாய்ப்பு",
        cat1_desc: "45 திட்டங்கள்",
        cat2_desc: "38 திட்டங்கள்",
        cat3_desc: "32 திட்டங்கள்",
        cat4_desc: "28 திட்டங்கள்",
        cat5_desc: "40 திட்டங்கள்",
        cat6_desc: "25 திட்டங்கள்",
        cat7_desc: "20 திட்டங்கள்",
        cat8_desc: "35 திட்டங்கள்",

        // About page
        aboutStory: "எங்கள் கதை",
        aboutTitle: 'ஜன-அசிஸ்ட்<br><span class="grad-text">பற்றி</span>',
        aboutDesc: "இந்தியாவின் மிகவும் நம்பகமான அரசு திட்ட தகுதி தளம் — 12 லட்சத்திற்கும் அதிகமான குடிமக்கள் தங்களுக்குத் தகுதியான நலத்திட்டங்களைக் கண்டறியவும், புரிந்துகொள்ளவும், அணுகவும் அதிகாரம் அளிக்கிறது.",
        aboutCheck: "தகுதி சரிபார்க்க",
        aboutBrowse: "திட்டங்களை உலாவுக",
        aboutScroll: "ஆராய கீழே உருட்டவும்",
        aboutStat1: "அரசு திட்டங்கள்",
        aboutStat2: "பயனடைந்த குடிமக்கள்",
        aboutStat3: "உள்ளடக்கிய மாநிலங்கள்",
        aboutStat4: "பாதுகாப்பான தளம்",
        aboutOffer: "நாங்கள் வழங்குவது",
        aboutOfferTitle: 'உங்களைச் சுற்றி <span class="grad-text">வடிவமைக்கப்பட்டது</span>',
        aboutOfferSub: "ஒவ்வொரு அம்சமும் சிரமங்களை நீக்கி, சரியான தகவலை உடனடியாக உங்கள் கைகளில் சேர்க்கும் வகையில் வடிவமைக்கப்பட்டுள்ளது.",
        aboutPurposeTitle: "எங்கள் நோக்கம்",
        aboutPurposeBody: "ஜன-அசிஸ்ட் குடிமக்களுக்கும் அரசு நலத்திட்டங்களுக்கும் இடையே உள்ள இடைவெளியைக் குறைக்கிறது. மில்லியன் கணக்கான தகுதியான குடிமக்கள் தங்களுக்குத் தகுதியான நன்மைகளைப் பற்றி அறியாமல் இருக்கிறார்கள் — அதை மாற்றவே நாங்கள் இருக்கிறோம். எங்கள் தளம் உங்கள் தனிப்பட்ட சுயவிவரத்தின் அடிப்படையில் கண்டறிதலை எளிதாக்குகிறது.",
        aboutPurposeTag: "முக்கிய நோக்கம்",
        aboutMissionTitle: "எங்கள் பணி",
        aboutMissionBody: "கல்வித் தகுதி, மொழி அல்லது இருப்பிடத்தைப் பொருட்படுத்தாமல் ஒவ்வொரு இந்தியக் குடிமகனுக்கும் அரசுத் திட்டத்தைக் கண்டறிவதை சிரமமின்றி மாற்றுவது. நலத்திட்டங்களுக்காக ஒதுக்கப்படும் ஒவ்வொரு ரூபாயும் அதைத் தேவைப்படுபவர்களைச் சென்றடைய வேண்டும் என்று நாங்கள் நம்புகிறோம்.",
        aboutMissionTag: "பணி சார்ந்த",
        aboutBenefitsTitle: "முக்கிய நன்மைகள்",
        aboutBenefitsBody: "வீட்டிலிருந்தே தகுதியைச் சரிபார்க்கவும் — வரிசைகள் இல்லை, காகித வேலைகள் இல்லை, குழப்பங்கள் இல்லை. எங்கள் உடனடி பொருத்த இயந்திரம் உத்தியோகபூர்வ அளவுகோல்களைப் பயன்படுத்தி உங்கள் வயது, வருமானம், தொழில், மாநிலம் மற்றும் பிரிவுக்கு மிகவும் பொருத்தமான திட்டங்களைக் காட்டுகிறது.",
        aboutBenefitsTag: "என்றென்றும் இலவசம்",
        aboutTransTitle: "முழு வெளிப்படைத்தன்மை",
        aboutTransBody: "ஒவ்வொரு திட்டத்திற்கும் தெளிவான, முழுமையான தகுதி அளவுகோல்களை நாங்கள் காட்டுகிறோம் — நேரடியாக அதிகாரப்பூர்வ அரசு ஆதாரங்களில் இருந்து. மறைக்கப்பட்ட படிகள் இல்லை. கட்டணங்கள் இல்லை. தவறான சுருக்கங்கள் இல்லை. நீங்கள் பார்ப்பது என்னவோ அதுவே தேவையானது.",
        aboutTransTag: "திறந்த தரவு",
        aboutAccessTitle: "அணுகல்தன்மைக்கு முன்னுரிமை",
        aboutAccessBody: "ஆங்கிலம், தமிழ், இந்தி, மலையாளம், தெலுங்கு மற்றும் கன்னடம் ஆகிய 6 பிராந்திய மொழிகளில் கிடைக்கிறது. எந்தவொரு சாதனத்திலும், எந்தத் திரை அளவிலும் மற்றும் கிராமப்புற இந்தியா முழுவதும் மெதுவான இணைய இணைப்புகளிலும் வேலை செய்யும் வகையில் வடிவமைக்கப்பட்டுள்ளது.",
        aboutAccessTag: "6 மொழிகள்",
        aboutGovtTitle: "திட்ட ஆதரவு",
        aboutGovtBody: "பிஎம்-கிசான் முதல் பேட்டி பச்சாவ் பேட்டி படாவ் வரை — கல்வி, விவசாயம், சுகாதாரம், வீட்டுவசதி, பெண்கள் நலம் மற்றும் பலவற்றில் 350+ மத்திய மற்றும் மாநில அரசு திட்டங்களை நாங்கள் உள்ளடக்குகிறோம். ஒவ்வொரு திட்டமும் அதன் அதிகாரப்பூர்வ அரசு போர்ட்டலுடன் இணைக்கப்பட்டுள்ளது.",
        aboutGovtTag: "350+ திட்டங்கள்",
        aboutQuote: "ஒவ்வொரு இந்திய குடிமகனும் தங்களுக்கு தகுதியான நலத்திட்டங்களை அறிந்து கொண்டு அவற்றை அணுக தகுதியானவர்கள். ஜன-அசிஸ்ட் அதை உண்மையாக்க பாடுபடுகிறது.",
        aboutCite: "— ஜன-அசிஸ்ட் குழு",
        aboutValuesTag: "எங்கள் மதிப்புகள்",
        aboutValuesTitle: "நாங்கள் எதற்காக நிற்கிறோம்",
        aboutV1: "குடிமக்களுக்கு முன்னுரிமை",
        aboutV2: "தரவு தனியுரிமை",
        aboutV3: "வேகம் & துல்லியம்",
        aboutV4: "இலவச & திறந்த",
        aboutV5: "பல மொழிகள்",
        aboutV6: "உள்ளடக்கிய வடிவமைப்பு",
        aboutV7: "100% பாதுகாப்பானது",
        aboutV8: "அரசு சரிபார்க்கப்பட்டது",
        aboutV9: "மொபைல் நட்பு",
        aboutV10: "எப்போதும் புதுப்பிக்கப்படும்",
        aboutCtaTitle: "தொடங்க தயாராக உள்ளீர்களா?",
        aboutCtaDesc: "ஏற்கனவே தங்கள் அரசு நன்மைகளைக் கண்டறிந்த 12 லட்சத்திற்கும் அதிகமான குடிமக்களுடன் இணையுங்கள். இதற்கு 2 நிமிடங்களுக்கும் குறைவாகவே ஆகும் — முற்றிலும் இலவசம்.",
        aboutCtaBtn: "என் தகுதியைச் சரிபார்க்கவும்",
        aboutFooter: "© 2026 JAN-ASSIST · அரசு உதவி, எளிமையாக",

        // Eligibility page
        eligEyebrow: "குடிமக்கள் சேவை போர்டல்",
        eligTitle: "உங்கள் தகுதியைச் சரிபார்க்கவும்",
        eligSub: "சில கேள்விகளுக்குப் பதிலளிக்கவும், எங்கள் அமைப்பு நீங்கள் தகுதிபெறும் ஒவ்வொரு அரசு நலத்திட்டத்துடனும் உங்களை உடனடியாகப் பொருத்தும்.",
        eligStep1: "சுயவிவரம்",
        eligStep2: "விவரங்கள்",
        eligStep3: "முடிவுகள்",
        eligSecA: "தனிப்பட்ட சுயவிவரம்",
        eligSecB: "பொருளாதார மற்றும் சமூக விவரங்கள்",
        eligName: "முழு பெயர்",
        eligNamePlaceholder: "உதாரணம்: குகன்",
        eligNameInvalid: "தயவுசெய்து உங்கள் முழுப் பெயரை உள்ளிடவும் (குறைந்தது 3 எழுத்துக்கள்)",
        eligAge: "வயது",
        eligAgePlaceholder: "18–100",
        eligAgeInvalid: "செல்லுபடியாகும் வயதை உள்ளிடவும் (1–120)",
        eligGender: "பாலினம்",
        eligGenderSelect: "தேர்வு செய்யவும்",
        eligGenderMale: "ஆண்",
        eligGenderFemale: "பெண்",
        eligGenderOther: "இதர",
        eligGenderInvalid: "பாலினத்தைத் தேர்ந்தெடுக்கவும்",
        eligState: "மாநிலம் / யூனியன் பிரதேசம்",
        eligStateSelect: "உங்கள் மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
        eligStateInvalid: "தயவுசெய்து உங்கள் மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
        eligOccupation: "தொழில்",
        eligOccSelect: "தொழிலைத் தேர்ந்தெடுக்கவும்",
        eligOccFarmer: "விவசாயி / விவசாய தொழிலாளி",
        eligOccSenior: "மூத்த குடிமகன்",
        eligOccStudent: "மாணவர்",
        eligOccUnemployed: "வேலையில்லாதவர்",
        eligOccHomemaker: "இல்லத்தரசி",
        eligOccRetired: "ஓய்வு பெற்றவர்",
        eligOccInvalid: "தயவுசெய்து உங்கள் தொழிலைத் தேர்ந்தெடுக்கவும்",
        eligIncome: "ஆண்டு குடும்ப வருமானம்",
        eligIncomeSub: "ஆண்டு குடும்ப வருமானம்",
        eligCategory: "சமூகப் பிரிவு",
        eligCatSelect: "பிரிவைத் தேர்ந்தெடுக்கவும்",
        eligCatGeneral: "பொது",
        eligCatObc: "OBC (இதர பிற்படுத்தப்பட்ட வகுப்பினர்)",
        eligCatSc: "SC (பட்டியலிடப்பட்ட சாதிகள்)",
        eligCatSt: "ST (பட்டியலிடப்பட்ட பழங்குடியினர்)",
        eligCatEws: "EWS (பொருளாதார ரீதியாக நலிவடைந்த பிரிவினர்)",
        eligCatMinority: "சிறுபான்மையினர் சமூகம்",
        eligCatInvalid: "தயவுசெய்து உங்கள் பிரிவைத் தேர்ந்தெடுக்கவும்",
        eligContact: "தொடர்பு எண்",
        eligContactPlaceholder: "மொபைல் எண்ணை உள்ளிடவும்",
        eligDataLoc: "உங்கள் தரவு உள்ளூரில் மட்டுமே செயலாக்கப்படுகிறது மற்றும் ஒருபோதும் சேமிக்கப்படாது.",
        eligScanBtn: "தகுதியை ஸ்கேன் செய்யவும்",
        eligResTitle: "தகுதி முடிவுகள்",
        eligResMeta: "ஏற்றப்படுகிறது…",
        eligStatMatched: "பொருந்திய திட்டங்கள்",
        eligStatTopScore: "சிறந்த பொருத்தம்",
        eligStatBenefit: "சாத்தியமான நன்மை",
        eligSearchPlaceholder: "திட்டத்தின் பெயர் அல்லது அமைச்சகம் மூலம் வடிகட்டவும்…",
        eligResNoMatch: "உங்கள் தேடலுடன் எந்த திட்டமும் பொருந்தவில்லை. வேறு வார்த்தைகளை முயற்சிக்கவும்.",
        eligRecheck: "புதிய சுயவிவரத்துடன் மீண்டும் சரிபார்க்கவும்",
        eligFooter: "© 2026 JAN-ASSIST · அரசு உதவி, எளிமையாக",

        // Schemes page
        schBadge: "உங்கள் நன்மைகளை உடனடியாகக் கண்டறியவும்",
        schTitle: 'அரசு திட்டங்களை<br><span class="gradient-text">ஆராயுங்கள்</span>',
        schSub: "இந்தியாவின் மிக விரிவான அரசு நலத்திட்டங்களின் தரவுத்தளத்தை ஆராயுங்கள். தேடுங்கள், வடிகட்டுங்கள் மற்றும் உங்கள் தேவைகளுக்கு ஏற்ற சரியான திட்டத்தைக் கண்டறியுங்கள் — அனைத்தும் ஒரே இடத்தில்.",
        schStatTotal: "மொத்த திட்டங்கள்",
        schStatCat: "பிரிவுகள்",
        schStatFree: "இலவச அணுகல்",
        schSearchBtn: "தேடுக",
        schSearchPlaceholder: "திட்டத்தின் பெயர், பிரிவு அல்லது விளக்கம் மூலம் தேடவும்...",
        schFilters: "வடிகட்டிகள்:",
        schCatAll: "அனைத்து பிரிவுகளும்",
        schCatEdu: "கல்வி",
        schCatHealth: "சுகாதாரம்",
        schCatAgri: "விவசாயம்",
        schCatWomen: "பெண்கள் நலம்",
        schCatSenior: "மூத்த குடிமக்கள்",
        schCatEmp: "வேலைவாய்ப்பு",
        schCatHousing: "வீட்டுவசதி",
        schCatChild: "குழந்தைகள் நலன்",
        schChipAll: "அனைத்தும்",
        schChipEdu: "கல்வி",
        schChipHealth: "சுகாதாரம்",
        schChipAgri: "விவசாயம்",
        schChipWomen: "பெண்கள்",
        schChipJobs: "வேலைகள்",
        schResultsCount: "திட்டங்கள் காட்டப்படுகின்றன",
        schModalEligTitle: "தகுதி அளவுகோல்",
        schModalBtn: "அதிகாரப்பூர்வ தளத்தைப் பார்வையிடவும்",
        schFooter: "© 2026 JAN-ASSIST. இந்திய மக்களுக்காக உருவாக்கப்பட்டது.",

        // Shared dynamic text (cards, details, copy)
        cardTopMatch: "சிறந்த பொருத்தம்",
        cardEligible: "தகுதியுடையவர்",
        cardEligMatch: "தகுதி பொருத்தம்",
        cardOfficialSite: "அதிகாரப்பூர்வ தளம்",
        cardVisitSite: "தளத்தைப் பார்க்க",
        cardViewDetails: "விவரங்களைப் பார்க்க",
        cardEligibilityLabel: "தகுதி:",
        cardNoSchemesFound: "திட்டங்கள் எதுவும் கிடைக்கவில்லை",
        cardNoSchemesSub: "உங்கள் தேடல் சொற்கள் அல்லது வடிகட்டி அளவுகோல்களை மாற்ற முயற்சிக்கவும்.",
        cardShowingSchemes: "Showing <span>{count}</span> scheme{plural}" // kept fallback as JS updates internally
    },
    hi: {
        // Navbar
        navHome: "होम",
        navAbout: "हमारे बारे में",
        navEligibility: "पात्रता जांचें",
        navSchemes: "योजनाएं",
        getStarted: "शुरू करें",

        // Index page
        badge: "⭐ 12 लाख+ नागरिकों द्वारा विश्वसनीय",
        title: '<span class="white-text">सरकारी सहायता,</span><br><span class="gradient-text">आसान बनाई गई</span>',
        sub: "केवल 2 मिनट में 350+ केंद्रीय और राज्य सरकारी योजनाओं के लिए अपनी पात्रता जांचें। मुफ्त, त्वरित और पूरी तरह से सुरक्षित।",
        search: "खोजें",
        stat1: "उपलब्ध योजनाएं",
        stat2: "मदद किए गए नागरिक",
        stat3: "शामिल राज्य",
        categoryTitle: "श्रेणी के अनुसार ब्राउज़ करें",
        categorySub: "विभिन्न सरकारी विभागों में अपनी आवश्यकताओं के अनुरूप योजनाएं खोजें",
        cat1: "शिक्षा",
        cat2: "कृषि",
        cat3: "महिला सशक्तिकरण",
        cat4: "वरिष्ठ नागरिक",
        cat5: "स्वास्थ्य सेवा",
        cat6: "आवास",
        cat7: "बाल कल्याण",
        cat8: "रोजगार",
        cat1_desc: "45 योजनाएं",
        cat2_desc: "38 योजनाएं",
        cat3_desc: "32 योजनाएं",
        cat4_desc: "28 योजनाएं",
        cat5_desc: "40 योजनाएं",
        cat6_desc: "25 योजनाएं",
        cat7_desc: "20 योजनाएं",
        cat8_desc: "35 योजनाएं",

        // About page
        aboutStory: "हमारी कहानी",
        aboutTitle: 'जन-असिस्ट के<br><span class="grad-text">बारे में</span>',
        aboutDesc: "भारत का सबसे भरोसेमंद सरकारी योजना पात्रता मंच — 12 लाख+ नागरिकों को उन कल्याणकारी कार्यक्रमों को खोजने, समझने और उन तक पहुंचने के लिए सशक्त बनाता है जिनके वे वास्तव में हकदार हैं।",
        aboutCheck: "पात्रता जांचें",
        aboutBrowse: "योजनाएं देखें",
        aboutScroll: "एक्सप्लोर करने के लिए स्क्रॉल करें",
        aboutStat1: "सरकारी योजनाएं",
        aboutStat2: "लाभान्वित नागरिक",
        aboutStat3: "शामिल राज्य",
        aboutStat4: "सुरक्षित प्लेटफॉर्म",
        aboutOffer: "हम क्या प्रदान करते हैं",
        aboutOfferTitle: 'विशेष रूप से आपके लिए <span class="grad-text">निर्मित</span>',
        aboutOfferSub: "हर सुविधा को कठिनाइयों को दूर करने और सही जानकारी तुरंत आपके हाथों में पहुंचाने के लिए डिज़ाइन किया गया है।",
        aboutPurposeTitle: "हमारा उद्देश्य",
        aboutPurposeBody: "जन-असिस्ट नागरिकों और सरकारी कल्याण कार्यक्रमों के बीच की खाई को पाटता है। लाखों पात्र नागरिक उन लाभों से अनभिज्ञ रहते हैं जिनके वे हकदार हैं — हम इसे बदलने के लिए मौजूद हैं। हमारा प्लेटफॉर्म आपकी व्यक्तिगत प्रोफाइल के आधार पर खोज को सरल बनाता है।",
        aboutPurposeTag: "मुख्य उद्देश्य",
        aboutMissionTitle: "हमारा मिशन",
        aboutMissionBody: "शिक्षा के स्तर, भाषा या स्थान की परवाह किए बिना प्रत्येक भारतीय नागरिक के लिए सरकारी योजना की खोज को आसान बनाना। हमारा मानना ​​है कि कल्याण के लिए निर्धारित हर रुपया उन लोगों तक पहुंचना चाहिए जिन्हें इसकी सबसे ज्यादा जरूरत है।",
        aboutMissionTag: "मिशन संचालित",
        aboutBenefitsTitle: "मुख्य लाभ",
        aboutBenefitsBody: "घर बैठे पात्रता जांचें — कोई कतार नहीं, कोई कागजी कार्रवाई नहीं, कोई भ्रम नहीं। हमारा त्वरित मिलान इंजन आपकी आयु, आय, व्यवसाय, राज्य और श्रेणी के लिए सबसे प्रासंगिक योजनाओं को प्रदर्शित करने के लिए आधिकारिक मानदंडों का उपयोग करता है।",
        aboutBenefitsTag: "हमेशा के लिए मुफ्त",
        aboutTransTitle: "पूर्ण पारदर्शिता",
        aboutTransBody: "हम हर योजना के लिए स्पष्ट, पूर्ण पात्रता मानदंड प्रदर्शित करते हैं — सीधे आधिकारिक सरकारी स्रोतों से। कोई छिपे हुए कदम नहीं। कोई भुगतान नहीं। कोई भ्रामक सारांश नहीं। जो आप देखते हैं वही आवश्यक है।",
        aboutTransTag: "ओपन डेटा",
        aboutAccessTitle: "सुलभता सर्वोपरि",
        aboutAccessBody: "6 क्षेत्रीय भाषाओं में उपलब्ध — अंग्रेजी, तमिल, हिंदी, मलयालम, तेलुगु और कन्नड़। किसी भी डिवाइस, किसी भी स्क्रीन आकार और ग्रामीण भारत में धीमे इंटरनेट कनेक्शन पर भी काम करने के लिए डिज़ाइन किया गया है।",
        aboutAccessTag: "6 भाषाएं",
        aboutGovtTitle: "योजना सहायता",
        aboutGovtBody: "पीएम-किसान से लेकर बेटी बचाओ बेटी पढ़ाओ तक — हम शिक्षा, कृषि, स्वास्थ्य सेवा, आवास, महिला कल्याण आदि में 350+ केंद्र और राज्य सरकार की योजनाओं को कवर करते हैं। हर योजना अपने आधिकारिक सरकारी पोर्टल से जुड़ती है।",
        aboutGovtTag: "350+ योजनाएं",
        aboutQuote: "भारत के प्रत्येक नागरिक को उन सभी कल्याणकारी योजनाओं के बारे में जानने और उन तक पहुँचने का अधिकार है जिनके वे हकदार हैं। जन-असिस्ट इसे वास्तविकता बनाने के लिए काम करता है।",
        aboutCite: "— जन-असिस्ट टीम",
        aboutValuesTag: "हमारे मूल्य",
        aboutValuesTitle: "हम किसके लिए प्रतिबद्ध हैं",
        aboutV1: "नागरिक प्रथम",
        aboutV2: "डेटा गोपनीयता",
        aboutV3: "गति और सटीकता",
        aboutV4: "मुफ्त और ओपन",
        aboutV5: "बहुभाषी",
        aboutV6: "समावेशी डिजाइन",
        aboutV7: "100% सुरक्षित",
        aboutV8: "सरकार द्वारा सत्यापित",
        aboutV9: "मोबाइल अनुकूल",
        aboutV10: "हमेशा अपडेटेड",
        aboutCtaTitle: "शुरू करने के लिए तैयार हैं?",
        aboutCtaDesc: "उन 12 लाख से अधिक नागरिकों में शामिल हों जिन्होंने पहले ही अपने सरकारी लाभों की खोज कर ली है। इसमें 2 मिनट से भी कम समय लगता है — और यह पूरी तरह से मुफ्त है।",
        aboutCtaBtn: "मेरी पात्रता जांचें",
        aboutFooter: "© 2026 JAN-ASSIST · सरकारी सहायता, आसान तरीके से",

        // Eligibility page
        eligEyebrow: "नागरिक सेवा पोर्टल",
        eligTitle: "अपनी पात्रता जांचें",
        eligSub: "कुछ सवालों के जवाब दें और हमारा सिस्टम आपको उन सभी सरकारी कल्याणकारी योजनाओं से मिलाएगा जिनके लिए आप योग्य हैं — तुरंत।",
        eligStep1: "प्रोफ़ाइल",
        eligStep2: "विवरण",
        eligStep3: "परिणाम",
        eligSecA: "व्यक्तिगत प्रोफ़ाइल",
        eligSecB: "आर्थिक और सामाजिक विवरण",
        eligName: "पूरा नाम",
        eligNamePlaceholder: "जैसे- गुगन",
        eligNameInvalid: "कृपया अपना पूरा नाम दर्ज करें (न्यूनतम 3 अक्षर)",
        eligAge: "आयु",
        eligAgePlaceholder: "18-100",
        eligAgeInvalid: "वैध आयु दर्ज करें (1-120)",
        eligGender: "लिंग",
        eligGenderSelect: "चुनें",
        eligGenderMale: "पुरुष",
        eligGenderFemale: "महिला",
        eligGenderOther: "अन्य",
        eligGenderInvalid: "कृपया लिंग का चयन करें",
        eligState: "राज्य / केंद्र शासित प्रदेश",
        eligStateSelect: "अपना राज्य चुनें",
        eligStateInvalid: "कृपया अपना राज्य चुनें",
        eligOccupation: "व्यवसाय",
        eligOccSelect: "व्यवसाय चुनें",
        eligOccFarmer: "किसान / कृषि श्रमिक",
        eligOccSenior: "वरिष्ठ नागरिक",
        eligOccStudent: "छात्र",
        eligOccUnemployed: "बेरोजगार",
        eligOccHomemaker: "गृहणी",
        eligOccRetired: "सेवानिवृत्त",
        eligOccInvalid: "कृपया अपना व्यवसाय चुनें",
        eligIncome: "वार्षिक पारिवारिक आय",
        eligIncomeSub: "वार्षिक पारिवारिक आय",
        eligCategory: "सामाजिक श्रेणी",
        eligCatSelect: "श्रेणी चुनें",
        eligCatGeneral: "सामान्य",
        eligCatObc: "ओबीसी (अन्य पिछड़ा वर्ग)",
        eligCatSc: "एससी (अनुसूचित जाति)",
        eligCatSt: "एसटी (अनुसूचित जनजाति)",
        eligCatEws: "ईडब्ल्यूएस (आर्थिक रूप से कमजोर वर्ग)",
        eligCatMinority: "अल्पसंख्यक समुदाय",
        eligCatInvalid: "कृपया अपनी श्रेणी चुनें",
        eligContact: "संपर्क नंबर",
        eligContactPlaceholder: "मोबाइल नंबर दर्ज करें",
        eligDataLoc: "आपका डेटा स्थानीय रूप से संसाधित किया जाता है और कभी संग्रहीत नहीं किया जाता है।",
        eligScanBtn: "पात्रता स्कैन करें",
        eligResTitle: "पात्रता परिणाम",
        eligResMeta: "लोड हो रहा है…",
        eligStatMatched: "मेल खाने वाली योजनाएं",
        eligStatTopScore: "सर्वश्रेष्ठ मैच",
        eligStatBenefit: "संभावित लाभ",
        eligSearchPlaceholder: "योजना के नाम या मंत्रालय द्वारा फ़िल्टर करें…",
        eligResNoMatch: "आपकी खोज से कोई योजना मेल नहीं खाती। विभिन्न कीवर्ड आज़माएं।",
        eligRecheck: "नई प्रोफ़ाइल के साथ फिर से जाँचें",
        eligFooter: "© 2026 JAN-ASSIST · सरकारी सहायता, आसान तरीके से",

        // Schemes page
        schBadge: "अपने लाभों की खोज तुरंत करें",
        schTitle: 'सरकारी योजनाओं का<br><span class="gradient-text">पता लगाएं</span>',
        schSub: "सरकारी कल्याणकारी योजनाओं के भारत के सबसे व्यापक डेटाबेस का अन्वेषण करें। खोजें, फ़िल्टर करें और अपनी आवश्यकताओं के लिए सही योजना खोजें — सब कुछ एक ही स्थान पर।",
        schStatTotal: "कुल योजनाएं",
        schStatCat: "श्रेणियां",
        schStatFree: "मुफ्त पहुंच",
        schSearchBtn: "खोजें",
        schSearchPlaceholder: "योजना के नाम, श्रेणी या विवरण द्वारा खोजें...",
        schFilters: "फ़िल्टर:",
        schCatAll: "सभी श्रेणियां",
        schCatEdu: "शिक्षा",
        schCatHealth: "स्वास्थ्य सेवा",
        schCatAgri: "कृषि",
        schCatWomen: "महिला कल्याण",
        schCatSenior: "वरिष्ठ नागरिक",
        schCatEmp: "रोजगार",
        schCatHousing: "आवास",
        schCatChild: "बाल कल्याण",
        schChipAll: "सभी",
        schChipEdu: "शिक्षा",
        schChipHealth: "स्वास्थ्य",
        schChipAgri: "कृषि",
        schChipWomen: "महिलाएं",
        schChipJobs: "नौकरियां",
        schResultsCount: "योजनाएं दिखाई जा रही हैं",
        schModalEligTitle: "पात्रता मापदंड",
        schModalBtn: "आधिकारिक वेबसाइट पर जाएं",
        schFooter: "© 2026 JAN-ASSIST. भारत के लोगों के लिए निर्मित।",

        // Shared dynamic text (cards, details, copy)
        cardTopMatch: "सर्वश्रेष्ठ मैच",
        cardEligible: "योग्य",
        cardEligMatch: "पात्रता मैच",
        cardOfficialSite: "आधिकारिक साइट",
        cardVisitSite: "साइट पर जाएं",
        cardViewDetails: "विवरण देखें",
        cardEligibilityLabel: "पात्रता:",
        cardNoSchemesFound: "कोई योजना नहीं मिली",
        cardNoSchemesSub: "अपने खोज शब्दों या फ़िल्टर मानदंडों को समायोजित करने का प्रयास करें।",
        cardShowingSchemes: "Showing <span>{count}</span> scheme{plural}"
    },
    te: {
        // Navbar
        navHome: "హోమ్",
        navAbout: "మా గురించి",
        navEligibility: "అర్హత తనిఖీ",
        navSchemes: "పథకాలు",
        getStarted: "ప్రారంభించండి",

        // Index page
        badge: "⭐ 12 లక్షల+ పౌరుల నమ్మకం",
        title: '<span class="white-text">ప్రభుత్వ సహాయం,</span><br><span class="gradient-text">సులభతరం చేయబడింది</span>',
        sub: "కేవలం 2 నిమిషాల్లో 350+ కేంద్ర మరియు రాష్ట్ర ప్రభుత్వ పథకాలకు మీ అర్హతను తనిఖీ చేయండి. ఉచితం, వేగవంతమైనది మరియు పూర్తిగా సురక్షితం.",
        search: "శోధించండి",
        stat1: "అందుబాటులో ఉన్న పథకాలు",
        stat2: "సహాయం పొందిన పౌరులు",
        stat3: "కవర్ చేయబడిన రాష్ట్రాలు",
        categoryTitle: "వర్గం వారీగా బ్రౌజ్ చేయండి",
        categorySub: "వివిధ ప్రభుత్వ విభాగాలలో మీ అవసరాలకు అనుగుణంగా పథకాలను కనుగొనండి",
        cat1: "విద్య",
        cat2: "వ్యవసాయం",
        cat3: "మహిళా సాధికారత",
        cat4: "వృద్ధ పౌరులు",
        cat5: "ఆరోగ్య సంరక్షణ",
        cat6: "గృహనిర్మాణం",
        cat7: "శిశు సంక్షేమం",
        cat8: "ఉపాధి",
        cat1_desc: "45 పథకాలు",
        cat2_desc: "38 పథకాలు",
        cat3_desc: "32 పథకాలు",
        cat4_desc: "28 పథకాలు",
        cat5_desc: "40 పథకాలు",
        cat6_desc: "25 పథకాలు",
        cat7_desc: "20 పథకాలు",
        cat8_desc: "35 పథకాలు",

        // About page
        aboutStory: "మా కథ",
        aboutTitle: 'జన-అసిస్ట్<br><span class="grad-text">గురించి</span>',
        aboutDesc: "భారతదేశం యొక్క అత్యంత విశ్వసనీయ ప్రభుత్వ పథకాల అర్హత వేదిక — 12 లక్షల కంటే ఎక్కువ మంది పౌరులు తమకు అర్హత ఉన్న సంక్షేమ కార్యక్రమాలను కనుగొనడానికి, అర్థం చేసుకోవడానికి మరియు యాక్సెస్ చేయడానికి వారికి అధికారం ఇస్తుంది.",
        aboutCheck: "అర్హత తనిఖీ",
        aboutBrowse: "పథకాలు బ్రౌజ్ చేయండి",
        aboutScroll: "అన్వేషించడానికి స్క్రోల్ చేయండి",
        aboutStat1: "ప్రభుత్వ పథకాలు",
        aboutStat2: "లబ్ధిపొందిన పౌరులు",
        aboutStat3: "కవర్ చేయబడిన రాష్ట్రాలు",
        aboutStat4: "సురక్షితమైన వేదిక",
        aboutOffer: "మేము ఏమి అందిస్తాము",
        aboutOfferTitle: 'మీ కోసం ప్రత్యేకంగా <span class="grad-text">రూపొందించబడింది</span>',
        aboutOfferSub: "ప్రతి ఫీచర్ ఇబ్బందులను తొలగించి, సరైన సమాచారాన్ని తక్షణమే మీ చేతుల్లోకి చేర్చేలా రూపొందించబడింది.",
        aboutPurposeTitle: "మా ఉద్దేశ్యం",
        aboutPurposeBody: "జన-అసిస్ట్ పౌరులకు మరియు ప్రభుత్వ సంక్షేమ కార్యక్రమాలకు మధ్య ఉన్న అంతరాన్ని పూడుస్తుంది. మిలియన్ల కొద్దీ అర్హులైన పౌరులు తమకు రావలసిన ప్రయోజనాల గురించి తెలియకుండానే ఉన్నారు — దానిని మార్చడానికి మేము ఉన్నాము. మా ప్లాట్‌ఫారమ్ మీ వ్యక్తిగత ప్రొఫైల్ ఆధారంగా పథకాలను కనుగొనడాన్ని సులభతరం చేస్తుంది.",
        aboutPurposeTag: "ప్రధాన ఉద్దేశ్యం",
        aboutMissionTitle: "మా లక్ష్యం",
        aboutMissionBody: "విద్యార్హత, భాష లేదా ప్రాంతంతో సంబంధం లేకుండా ప్రతి భారతీయ పౌరుడికి ప్రభుత్వ పథకాలను కనుగొనడం సులభతరం చేయడం. సంక్షేమం కోసం కేటాయించిన ప్రతి రూపాయి అత్యంత అవసరమైన వారికి చేరాలని మేము నమ్ముతున్నాము.",
        aboutMissionTag: "లక్ష్య ఆధారిత",
        aboutBenefitsTitle: "ముఖ్య ప్రయోజనాలు",
        aboutBenefitsBody: "ఇంటి నుండే అర్హతను తనిఖీ చేసుకోండి — క్యూలు లేవు, పత్రాల పని లేదు, గందరగోళం లేదు. మా తక్షణ మ్యాచింగ్ ఇంజిన్ మీ వయస్సు, ఆదాయం, వృత్తి, రాష్ట్రం మరియు వర్గానికి అత్యంత సంబంధిత పథకాలను చూపించడానికి అధికారిక ప్రమాణాలను ఉపయోగిస్తుంది.",
        aboutBenefitsTag: "ఎల్లప్పుడూ ఉచితం",
        aboutTransTitle: "పూర్తి పారదర్శకత",
        aboutTransBody: "మేము ప్రతి పథకానికి స్పష్టమైన, పూర్తి అర్హత ప్రమాణాలను ప్రదర్శిస్తాము — నేరుగా అధికారిక ప్రభుత్వ వనరుల నుండి. దాచిన దశలు లేవు. ఎలాంటి రుసుములు లేవు. తప్పుదోవ పట్టించే సారాంశాలు లేవు. మీరు చూసేది సరిగ్గా అవసరమైనది.",
        aboutTransTag: "ఓపెన్ డేటా",
        aboutAccessTitle: "యాక్సెస్ ప్రాధాన్యత",
        aboutAccessBody: "ఇంగ్లీష్, తమిళం, హిందీ, మలయాళం, తెలుగు మరియు కన్నడ అనే 6 ప్రాంతీయ భాషలలో అందుబాటులో ఉంది. ఏ పరికరంలోనైనా, ఏ స్క్రీన్ పరిమాణంలోనైనా మరియు గ్రామీణ భారతదేశంలో నెమ్మదిగా ఉన్న ఇంటర్నెట్ కనెక్షన్లలో కూడా పనిచేసేలా రూపొందించబడింది.",
        aboutAccessTag: "6 భాషలు",
        aboutGovtTitle: "పథకాల మద్దతు",
        aboutGovtBody: "పీఎం-కిసాన్ నుండి బేటీ బచావో బేటీ పఢావో వరకు — మేము విద్య, వ్యవసాయం, ఆరోగ్య సంరక్షణ, గృహ నిర్మాణం, మహిళా సంక్షేమం మరియు మరిన్ని విభాగాలలో 350+ కేంద్ర మరియు రాష్ట్ర ప్రభుత్వ పథకాలను కవర్ చేస్తాము. ప్రతి పథకం దాని అధికారిక ప్రభుత్వ పోర్టల్‌కు లింక్ చేయబడింది.",
        aboutGovtTag: "350+ పథకాలు",
        aboutQuote: "భారతదేశ పౌరులందరికీ తమకు అర్హత ఉన్న సంక్షేమ పథకాలను తెలుసుకునే హక్కు ఉంది. జన-అసిస్ట్ దానిని సాకారం చేస్తుంది.",
        aboutCite: "— జన-అసిస్ట్ బృందం",
        aboutValuesTag: "మా విలువలు",
        aboutValuesTitle: "మేము దేనికి కట్టుబడి ఉన్నాము",
        aboutV1: "పౌరుడే ప్రథమం",
        aboutV2: "డేటా గోప్యత",
        aboutV3: "వేగం & ఖచ్చితత్వం",
        aboutV4: "ఉచితం & ఓపెన్",
        aboutV5: "బహుభాషా",
        aboutV6: "సమ్మిళిత డిజైన్",
        aboutV7: "100% సురక్షితం",
        aboutV8: "ప్రభుత్వ ధృవీకృత",
        aboutV9: "మొబైల్ అనుకూలమైనది",
        aboutV10: "ఎల్లప్పుడూ అప్‌డేట్ చేయబడుతుంది",
        aboutCtaTitle: "ప్రారంభించడానికి సిద్ధంగా ఉన్నారా?",
        aboutCtaDesc: "ఇప్పటికే తమ ప్రభుత్వ ప్రయోజనాలను కనుగొన్న 12 లక్షల కంటే ఎక్కువ మంది పౌరులలో చేరండి. దీనికి 2 నిమిషాల కంటే తక్కువ సమయం పడుతుంది — మరియు ఇది పూర్తిగా ఉచితం.",
        aboutCtaBtn: "నా అర్హతను తనిఖీ చేయండి",
        aboutFooter: "© 2026 JAN-ASSIST · ప్రభుత్వ సహాయం, సులభంగా",

        // Eligibility page
        eligEyebrow: "పౌర సేవల పోర్టల్",
        eligTitle: "మీ అర్హతను తనిఖీ చేయండి",
        eligSub: "కొన్ని ప్రశ్నలకు సమాధానం ఇవ్వండి మరియు మీరు అర్హత పొందే ప్రతి ప్రభుత్వ సంక్షేమ పథకంతో మా సిస్టమ్ మిమ్మల్ని తక్షణమే సరిపోలుస్తుంది.",
        eligStep1: "ప్రొఫైల్",
        eligStep2: "వివరాలు",
        eligStep3: "ఫలితాలు",
        eligSecA: "వ్యక్తిగత ప్రొఫైల్",
        eligSecB: "ఆర్థిక మరియు సామాజిక వివరాలు",
        eligName: "పూర్తి పేరు",
        eligNamePlaceholder: "ఉదాహరణ: గుగన్",
        eligNameInvalid: "దయచేసి మీ పూర్తి పేరును నమోదు చేయండి (కనీసం 3 అక్షరాలు)",
        eligAge: "వయస్సు",
        eligAgePlaceholder: "18-100",
        eligAgeInvalid: "చెల్లుబాటు అయ్యే వయస్సును నమోదు చేయండి (1-120)",
        eligGender: "లింగం",
        eligGenderSelect: "ఎంచుకోండి",
        eligGenderMale: "పురుషుడు",
        eligGenderFemale: "స్త్రీ",
        eligGenderOther: "ఇతర",
        eligGenderInvalid: "దయచేసి లింగాన్ని ఎంచుకోండి",
        eligState: "రాష్ట్రం / కేంద్రపాలిత ప్రాంతం",
        eligStateSelect: "మీ రాష్ట్రాన్ని ఎంచుకోండి",
        eligStateInvalid: "దయచేసి మీ రాష్ట్రాన్ని ఎంచుకోండి",
        eligOccupation: "వృత్తి",
        eligOccSelect: "వృత్తిని ఎంచుకోండి",
        eligOccFarmer: "రైతు / వ్యవసాయ కార్మికుడు",
        eligOccSenior: "వృద్ధ పౌరుడు",
        eligOccStudent: "విద్యార్థి",
        eligOccUnemployed: "నిరుద్యోగి",
        eligOccHomemaker: "గృహిణి",
        eligOccRetired: "పదవీ విరమణ చేసినవారు",
        eligOccInvalid: "దయచేసి మీ వృత్తిని ఎంచుకోండి",
        eligIncome: "వార్షిక కుటుంబ ఆదాయం",
        eligIncomeSub: "వార్షిక కుటుంబ ఆదాయం",
        eligCategory: "సామాజిక వర్గం",
        eligCatSelect: "వర్గాన్ని ఎంచుకోండి",
        eligCatGeneral: "జనరల్",
        eligCatObc: "OBC (ఇతర వెనుకబడిన తరగతులు)",
        eligCatSc: "SC (షెడ్యూల్డ్ కులాలు)",
        eligCatSt: "ST (షెడ్యూల్డ్ తెగలు)",
        eligCatEws: "EWS (ఆర్థికంగా బలహీన వర్గాలు)",
        eligCatMinority: "మైనారిటీ కమ్యూనిటీ",
        eligCatInvalid: "దయచేసి మీ వర్గాన్ని ఎంచుకోండి",
        eligContact: "సంప్రదించవలసిన సంఖ్య",
        eligContactPlaceholder: "మొబైల్ సంఖ్యను నమోదు చేయండి",
        eligDataLoc: "మీ డేటా స్థానికంగా ప్రాసెస్ చేయబడుతుంది మరియు ఎప్పటికీ నిల్వ చేయబడదు.",
        eligScanBtn: "అర్హతను స్కాన్ చేయండి",
        eligResTitle: "అర్హత ఫలితాలు",
        eligResMeta: "లోడ్ అవుతోంది…",
        eligStatMatched: "సరిపోలిన పథకాలు",
        eligStatTopScore: "టాప్ మ్యాచ్",
        eligStatBenefit: "సంభావ్య ప్రయోజనం",
        eligSearchPlaceholder: "పథకం పేరు లేదా మంత్రిత్వ శాఖ ద్వారా ఫిల్టర్ చేయండి…",
        eligResNoMatch: "మీ శోధనకు సరిపోలే పథకాలు లేవు. విభిన్న కీలకపదాలను ప్రయత్నించండి.",
        eligRecheck: "కొత్త ప్రొఫైల్‌తో మళ్లీ తనిఖీ చేయండి",
        eligFooter: "© 2026 JAN-ASSIST · ప్రభుత్వ సహాయం, సులభంగా",

        // Schemes page
        schBadge: "మీ ప్రయోజనాలను తక్షణమే కనుగొనండి",
        schTitle: 'ప్రభుత్వ పథకాలను<br><span class="gradient-text">అన్వేషించండి</span>',
        schSub: "ప్రభుత్వ సంక్షేమ పథకాల భారతదేశపు అత్యంత సమగ్రమైన డేటాబేస్ను నావిగేట్ చేయండి. శోధించండి, ఫిల్టర్ చేయండి మరియు మీ అవసరాలకు తగిన పథకాన్ని కనుగొనండి — అన్నీ ఒకే చోట.",
        schStatTotal: "మొత్తం పథకాలు",
        schStatCat: "వర్గాలు",
        schStatFree: "ఉచిత యాక్సెస్",
        schSearchBtn: "శోధించు",
        schSearchPlaceholder: "పథకం పేరు, వర్గం లేదా వివరణ ద్వారా శోధించండి...",
        schFilters: "ఫిల్టర్లు:",
        schCatAll: "అన్ని వర్గాలు",
        schCatEdu: "విద్య",
        schCatHealth: "ఆరోగ్య సంరక్షణ",
        schCatAgri: "వ్యవసాయం",
        schCatWomen: "మహిళా సంక్షేమం",
        schCatSenior: "వృద్ధ పౌరులు",
        schCatEmp: "ఉపాధి",
        schCatHousing: "గృహనిర్మాణం",
        schCatChild: "శిశు సంక్షేమం",
        schChipAll: "అన్నీ",
        schChipEdu: "విద్య",
        schChipHealth: "ఆరోగ్యం",
        schChipAgri: "వ్యవసాయం",
        schChipWomen: "మహిళలు",
        schChipJobs: "ఉద్యోగాలు",
        schResultsCount: "పథకాలను చూపిస్తోంది",
        schModalEligTitle: "అర్హత ప్రమాణాలు",
        schModalBtn: "అధికారిక వెబ్‌సైట్‌ను సందర్శించండి",
        schFooter: "© 2026 JAN-ASSIST. భారతదేశ ప్రజల కోసం నిర్మించబడింది.",

        // Shared dynamic text (cards, details, copy)
        cardTopMatch: "టాప్ మ్యాచ్",
        cardEligible: "అర్హులు",
        cardEligMatch: "అర్హత మ్యాచ్",
        cardOfficialSite: "అధికారిక సైట్",
        cardVisitSite: "సైట్ సందర్శించండి",
        cardViewDetails: "వివరాలు చూడండి",
        cardEligibilityLabel: "అర్హత:",
        cardNoSchemesFound: "పథకాలు ఏవీ కనుగొనబడలేదు",
        cardNoSchemesSub: "మీ శోధన పదాలను లేదా ఫిల్టర్ ప్రమాణాలను సర్దుబాటు చేయడానికి ప్రయత్నించండి.",
        cardShowingSchemes: "Showing <span>{count}</span> scheme{plural}"
    },
    ml: {
        // Navbar
        navHome: "ഹോം",
        navAbout: "ഞങ്ങളെ കുറിച്ച്",
        navEligibility: "യോഗ്യത പരിശോധിക്കുക",
        navSchemes: "പദ്ധതികൾ",
        getStarted: "ആരംഭിക്കുക",

        // Index page
        badge: "⭐ 12 ലക്ഷത്തിലധികം പൗരന്മാരുടെ വിശ്വാസം",
        title: '<span class="white-text">ഗവൺമെന്റ് പിന്തുണ,</span><br><span class="gradient-text">ലളിതമാക്കിയിരിക്കുന്നു</span>',
        sub: "വെറും 2 മിനിറ്റിനുള്ളിൽ 350+ കേന്ദ്ര-സംസ്ഥാന സർക്കാർ പദ്ധതികൾക്കായി നിങ്ങളുടെ യോഗ്യത പരിശോധിക്കുക. തികച്ചും സൗജന്യവും വേഗതയേറിയതും സുരക്ഷിതവുമാണ്.",
        search: "തിരയുക",
        stat1: "ലഭ്യമായ പദ്ധതികൾ",
        stat2: "സഹായിച്ച പൗരന്മാർ",
        stat3: "ഉൾപ്പെടുത്തിയ സംസ്ഥാനങ്ങൾ",
        categoryTitle: "വിഭാഗം അനുസരിച്ച് ബ്രൗസ് ചെയ്യുക",
        categorySub: "വിവിധ സർക്കാർ വകുപ്പുകളിലായി നിങ്ങളുടെ ആവശ്യങ്ങൾക്ക് അനുയോജ്യമായ പദ്ധതികൾ കണ്ടെത്തുക",
        cat1: "വിദ്യാഭ്യാസം",
        cat2: "കൃഷി",
        cat3: "വനിതാ ശാക്തീകരണം",
        cat4: "മുതിർന്ന പൗരന്മാർ",
        cat5: "ആരോഗ്യ സംരക്ഷണം",
        cat6: "ഭവന നിർമ്മാണം",
        cat7: "ശിശുക്ഷേമം",
        cat8: "തൊഴിൽ",
        cat1_desc: "45 പദ്ധതികൾ",
        cat2_desc: "38 പദ്ധതികൾ",
        cat3_desc: "32 പദ്ധതികൾ",
        cat4_desc: "28 പദ്ധതികൾ",
        cat5_desc: "40 പദ്ധതികൾ",
        cat6_desc: "25 പദ്ധതികൾ",
        cat7_desc: "20 പദ്ധതികൾ",
        cat8_desc: "35 പദ്ധതികൾ",

        // About page
        aboutStory: "ഞങ്ങളുടെ കഥ",
        aboutTitle: 'ജന-അസിസ്റ്റിനെ<br><span class="grad-text">കുറിച്ച്</span>',
        aboutDesc: "ഇന്ത്യയിലെ ഏറ്റവും വിശ്വസനീയമായ സർക്കാർ പദ്ധതി യോഗ്യതാ പ്ലാറ്റ്ഫോം — 12 ലക്ഷത്തിലധികം പൗരന്മാർക്ക് അവർ അർഹിക്കുന്ന ക്ഷേമപദ്ധതികൾ കണ്ടെത്താനും മനസ്സിലാക്കാനും ലഭ്യമാക്കാനും അവരെ പ്രാപ്തരാക്കുന്നു.",
        aboutCheck: "യോഗ്യത പരിശോധിക്കുക",
        aboutBrowse: "പദ്ധതികൾ ബ്രൗസ് ചെയ്യുക",
        aboutScroll: "കൂടുതലറിയാൻ സ്ക്രോൾ ചെയ്യുക",
        aboutStat1: "സർക്കാർ പദ്ധതികൾ",
        aboutStat2: "പിന്തുണച്ച പൗരന്മാർ",
        aboutStat3: "ഉൾപ്പെടുത്തിയ സംസ്ഥാനങ്ങൾ",
        aboutStat4: "സുരക്ഷിത പ്ലാറ്റ്ഫോം",
        aboutOffer: "ഞങ്ങൾ നൽകുന്നത്",
        aboutOfferTitle: 'നിങ്ങൾക്കായി <span class="grad-text">രൂപകൽപ്പന ചെയ്തത്</span>',
        aboutOfferSub: "എല്ലാ സവിശേഷതകളും ബുദ്ധിമുട്ടുകൾ ഒഴിവാക്കാനും ശരിയായ വിവരങ്ങൾ നിങ്ങളുടെ കൈകളിൽ എത്തിക്കാനുമായി രൂപകൽപ്പന ചെയ്തതാണ്.",
        aboutPurposeTitle: "ഞങ്ങളുടെ ലക്ഷ്യം",
        aboutPurposeBody: "ജന-അസിസ്റ്റ് പൗരന്മാരും സർക്കാർ ക്ഷേമപദ്ധതികളും തമ്മിലുള്ള അകലം കുറയ്ക്കുന്നു. ദശലക്ഷക്കണക്കിന് അർഹരായ പൗരന്മാർ തങ്ങൾക്ക് അർഹമായ ആനുകൂല്യങ്ങളെക്കുറിച്ച് ഇപ്പോഴും അജ്ഞരാണ് — ഇത് മാറ്റാൻ ഞങ്ങളുണ്ട്. ഞങ്ങളുടെ പ്ലാറ്റ്ഫോം നിങ്ങളുടെ വ്യക്തിഗത പ്രൊഫൈൽ അടിസ്ഥാനമാക്കി കണ്ടെത്തൽ ലളിതമാക്കുന്നു.",
        aboutPurposeTag: "പ്രധാന ലക്ഷ്യം",
        aboutMissionTitle: "ഞങ്ങളുടെ ദൗത്യം",
        aboutMissionBody: "വിദ്യാഭ്യാസ നിലവാരമോ ഭാഷയോ സ്ഥലമോ പരിഗണിക്കാതെ എല്ലാ ഇന്ത്യൻ പൗരന്മാർക്കും സർക്കാർ പദ്ധതി കണ്ടെത്തൽ സുഗമമാക്കുക. ക്ഷേമത്തിനായി നീക്കിവെക്കുന്ന ഓരോ രൂപയും ഏറ്റവും ആവശ്യമുള്ളവരിലേക്ക് എത്തണമെന്ന് ഞങ്ങൾ വിശ്വസിക്കുന്നു.",
        aboutMissionTag: "ദൗത്യം നയിക്കുന്നത്",
        aboutBenefitsTitle: "പ്രധാന ഗുണങ്ങൾ",
        aboutBenefitsBody: "വീട്ടിലിരുന്ന് യോഗ്യത പരിശോധിക്കാം — ക്യൂ നിൽക്കേണ്ടതില്ല, പേപ്പർവർക്കുകളില്ല, ആശയക്കുഴപ്പമില്ല. ഞങ്ങളുടെ തൽക്ഷണ മാച്ചിംഗ് എഞ്ചിൻ ഔദ്യോഗിക മാനദണ്ഡങ്ങൾ ഉപയോഗിച്ച് നിങ്ങളുടെ പ്രായം, വരുമാനം, തൊഴിൽ, സംസ്ഥാനം, വിഭാഗം എന്നിവയ്ക്ക് അനുയോജ്യമായ പദ്ധതികൾ കാണിക്കുന്നു.",
        aboutBenefitsTag: "സൗജന്യം എപ്പോഴും",
        aboutTransTitle: "പൂർണ്ണ സുതാര്യത",
        aboutTransBody: "ഓരോ പദ്ധതിക്കും വ്യക്തവും പൂർണ്ണവുമായ യോഗ്യതാ മാനദണ്ഡങ്ങൾ ഞങ്ങൾ കാണിക്കുന്നു — നേരിട്ട് ഔദ്യോഗിക സർക്കാർ സ്രോതസ്സുകളിൽ നിന്ന്. മറഞ്ഞിരിക്കുന്ന ഘട്ടങ്ങളില്ല. പണച്ചെലവില്ല. തെറ്റിദ്ധരിപ്പിക്കുന്ന സംഗ്രഹങ്ങളില്ല. നിങ്ങൾ കാണുന്നത് തന്നെയാണ് ആവശ്യമായത്.",
        aboutTransTag: "തുറന്ന ഡാറ്റ",
        aboutAccessTitle: "ആക്സസ്സിബിലിറ്റിക്ക് മുൻഗണന",
        aboutAccessBody: "ആംഗലേയത്തിലും കൂടാതെ തമിഴ്, ഹിന്ദി, മലയാളം, തെലുങ്ക്, കന്നഡ എന്നീ 5 പ്രാദേശിക ഭാഷകളിലും ലഭ്യമാണ്. ഏത് ഉപകരണത്തിലും, ഏത് സ്ക്രീൻ വലുപ്പത്തിലും, ഗ്രാമീണ ഇന്ത്യയിലെ മന്ദഗതിയിലുള്ള ഇന്റർനെറ്റ് കണക്ഷനുകളിൽ പോലും പ്രവർത്തിക്കാൻ രൂപകൽപ്പന ചെയ്‌തിരിക്കുന്നു.",
        aboutAccessTag: "6 ഭാഷകൾ",
        aboutGovtTitle: "പദ്ധതി പിന്തുണ",
        aboutGovtBody: "പിഎം-കിസാൻ മുതൽ ബേട്ടി ബച്ചാവോ ബേട്ടി പഠാവോ വരെ — വിദ്യാഭ്യാസം, കൃഷി, ആരോഗ്യം, ഭവനം, വനിതാ ക്ഷേമം എന്നിവയിലുടനീളം 350+ കേന്ദ്ര-സംസ്ഥാന സർക്കാർ പദ്ധതികൾ ഞങ്ങൾ ഉൾക്കൊള്ളുന്നു. ഓരോ പദ്ധതിയും അതിന്റെ ഔദ്യോഗിക സർക്കാർ പോർട്ടലിലേക്ക് ബന്ധിപ്പിച്ചിരിക്കുന്നു.",
        aboutGovtTag: "350+ പദ്ധതികൾ",
        aboutQuote: "അർഹതയുള്ള എല്ലാ ക്ഷേമപദ്ധതികളെക്കുറിച്ചും അറിയാനും അവ ലഭ്യമാക്കാനും ഇന്ത്യയിലെ ഓരോ പൗരനും അവകാശമുണ്ട്. ജന-അസിസ്റ്റ് അത് യാഥാർത്ഥ്യമാക്കുന്നു.",
        aboutCite: "— ജന-അസിസ്റ്റ് ടീം",
        aboutValuesTag: "ഞങ്ങളുടെ മൂല്യങ്ങൾ",
        aboutValuesTitle: "ഞങ്ങൾ നിലകൊള്ളുന്നത് എന്തിനാണ്",
        aboutV1: "പൗരൻ പ്രഥമം",
        aboutV2: "ഡാറ്റാ സ്വകാര്യത",
        aboutV3: "വേഗതയും കൃത്യതയും",
        aboutV4: "സൗജന്യവും തുറന്നതും",
        aboutV5: "ബഹുഭാഷാ",
        aboutV6: "ഉൾക്കൊള്ളുന്ന ഡിസൈൻ",
        aboutV7: "100% സുരക്ഷിതം",
        aboutV8: "ഗവൺമെന്റ് വെരിഫൈഡ്",
        aboutV9: "മൊബൈൽ ഫ്രണ്ട്‌ലി",
        aboutV10: "എപ്പോഴും അപ്‌ഡേറ്റഡ്",
        aboutCtaTitle: "ആരംഭിക്കാൻ തയ്യാറാണോ?",
        aboutCtaDesc: "ഇതിനകം തങ്ങളുടെ സർക്കാർ ആനുകൂല്യങ്ങൾ കണ്ടെത്തിയ 12 ലക്ഷത്തിലധികം പൗരന്മാർക്കൊപ്പം ചേരൂ. വെറും 2 മിനിറ്റിൽ താഴെ സമയം മാത്രം — തികച്ചും സൗജന്യമാണ്.",
        aboutCtaBtn: "എന്റെ യോഗ്യത പരിശോധിക്കുക",
        aboutFooter: "© 2026 JAN-ASSIST · ഗവൺമെന്റ് പിന്തുണ, ലളിതമായി",

        // Eligibility page
        eligEyebrow: "സിറ്റിസൺ സർവീസസ് പോർട്ടൽ",
        eligTitle: "നിങ്ങളുടെ യോഗ്യത പരിശോധിക്കുക",
        eligSub: "ചില ചോദ്യങ്ങൾക്ക് മറുപടി നൽകുക, ഞങ്ങളുടെ സിസ്റ്റം നിങ്ങൾ യോഗ്യത നേടുന്ന എല്ലാ സർക്കാർ ക്ഷേമപദ്ധതികളുമായി നിങ്ങളെ തൽക്ഷണം പൊരുത്തപ്പെടുത്തും.",
        eligStep1: "പ്രൊഫൈൽ",
        eligStep2: "വിവരങ്ങൾ",
        eligStep3: "ഫലങ്ങൾ",
        eligSecA: "വ്യക്തിഗത പ്രൊഫൈൽ",
        eligSecB: "സാമ്പത്തികവും സാമൂഹികവുമായ വിവരങ്ങൾ",
        eligName: "പൂർണ്ണമായ പേര്",
        eligNamePlaceholder: "ഉദാഹരണത്തിന്: ഗുഗൻ",
        eligNameInvalid: "ദയവായി നിങ്ങളുടെ പൂർണ്ണമായ പേര് നൽകുക (കുറഞ്ഞത് 3 അക്ഷരങ്ങൾ)",
        eligAge: "പ്രായം",
        eligAgePlaceholder: "18-100",
        eligAgeInvalid: "ശരിയായ പ്രായം നൽകുക (1-120)",
        eligGender: "ലിംഗഭേദം",
        eligGenderSelect: "തിരഞ്ഞെടുക്കുക",
        eligGenderMale: "പുരുഷൻ",
        eligGenderFemale: "സ്ത്രീ",
        eligGenderOther: "മറ്റുള്ളവ",
        eligGenderInvalid: "ദയവായി ലിംഗഭേദം തിരഞ്ഞെടുക്കുക",
        eligState: "സംസ്ഥാനം / കേന്ദ്രഭരണ പ്രദേശം",
        eligStateSelect: "നിങ്ങളുടെ സംസ്ഥാനം തിരഞ്ഞെടുക്കുക",
        eligStateInvalid: "ദയവായി നിങ്ങളുടെ സംസ്ഥാനം തിരഞ്ഞെടുക്കുക",
        eligOccupation: "തൊഴിൽ",
        eligOccSelect: "തൊഴിൽ തിരഞ്ഞെടുക്കുക",
        eligOccFarmer: "കർഷകൻ / കാർഷിക തൊഴിലാളി",
        eligOccSenior: "മുതിർന്ന പൗരൻ",
        eligOccStudent: "വിദ്യാർത്ഥി",
        eligOccUnemployed: "തൊഴിൽ രഹിതൻ",
        eligOccHomemaker: "ഗൃഹനായിക",
        eligOccRetired: "വിരമിച്ചവർ",
        eligOccInvalid: "ദയവായി നിങ്ങളുടെ തൊഴിൽ തിരഞ്ഞെടുക്കുക",
        eligIncome: "വാർഷിക കുടുംബ വരുമാനം",
        eligIncomeSub: "വാർഷിക കുടുംബ വരുമാനം",
        eligCategory: "സാമൂഹിക വിഭാഗം",
        eligCatSelect: "വിഭാഗം തിരഞ്ഞെടുക്കുക",
        eligCatGeneral: "ജനറൽ",
        eligCatObc: "OBC (മറ്റ് പിന്നാക്ക വിഭാഗങ്ങൾ)",
        eligCatSc: "SC (പട്ടികജാതി)",
        eligCatSt: "ST (പട്ടികവർഗ്ഗം)",
        eligCatEws: "EWS (സാമ്പത്തികമായി പിന്നാക്കം നിൽക്കുന്ന വിഭാഗം)",
        eligCatMinority: "ന്യൂനപക്ഷ വിഭാഗം",
        eligCatInvalid: "ദയവായി നിങ്ങളുടെ വിഭാഗം തിരഞ്ഞെടുക്കുക",
        eligContact: "ബന്ധപ്പെടേണ്ട നമ്പർ",
        eligContactPlaceholder: "മൊബൈൽ നമ്പർ നൽകുക",
        eligDataLoc: "നിങ്ങളുടെ ഡാറ്റ പ്രാദേശികമായി മാത്രമേ പ്രോസസ്സ് ചെയ്യുകയുള്ളൂ, ഒരിക്കലും സൂക്ഷിക്കുകയില്ല.",
        eligScanBtn: "യോഗ്യത സ്കാൻ ചെയ്യുക",
        eligResTitle: "യോഗ്യതാ ഫലങ്ങൾ",
        eligResMeta: "ലോഡ് ചെയ്യുന്നു…",
        eligStatMatched: "പൊരുത്തപ്പെട്ട പദ്ധതികൾ",
        eligStatTopScore: "മികച്ച പൊരുത്തം",
        eligStatBenefit: "സാധ്യമായ ആനുകൂല്യം",
        eligSearchPlaceholder: "പദ്ധതിയുടെ പേരോ മന്ത്രാലയമോ ഉപയോഗിച്ച് ഫിൽട്ടർ ചെയ്യുക…",
        eligResNoMatch: "നിങ്ങളുടെ തിരച്ചിലിന് അനുയോജ്യമായ പദ്ധതികളൊന്നും കണ്ടെത്തിയില്ല. മറ്റ് വാക്കുകൾ പരീക്ഷിക്കുക.",
        eligRecheck: "പുതിയ പ്രൊഫൈൽ ഉപയോഗിച്ച് വീണ്ടും പരിശോധിക്കുക",
        eligFooter: "© 2026 JAN-ASSIST · ഗവൺമെന്റ് പിന്തുണ, ലളിതമായി",

        // Schemes page
        schBadge: "നിങ്ങളുടെ ആനുകൂല്യങ്ങൾ തൽക്ഷണം കണ്ടെത്തുക",
        schTitle: 'സർക്കാർ പദ്ധതികൾ<br><span class="gradient-text">അന്വേഷിക്കുക</span>',
        schSub: "സർക്കാർ ക്ഷേമപദ്ധതികളുടെ ഇന്ത്യയിലെ ഏറ്റവും സമഗ്രമായ ഡാറ്റാബേസ് പരിശോധിക്കുക. തിരയുക, ഫിൽട്ടർ ചെയ്യുക, നിങ്ങളുടെ ആവശ്യങ്ങൾക്ക് അനുയോജ്യമായ പദ്ധതി കണ്ടെത്തുക — എല്ലാം ഒരിടത്ത്.",
        schStatTotal: "ആകെ പദ്ധതികൾ",
        schStatCat: "വിഭാഗങ്ങൾ",
        schStatFree: "സൗജന്യ ആക്സസ്",
        schSearchBtn: "തിരയുക",
        schSearchPlaceholder: "പദ്ധതിയുടെ പേര്, വിഭാഗം അല്ലെങ്കിൽ വിവരണം അനുസരിച്ച് തിരയുക...",
        schFilters: "ഫിൽട്ടറുകൾ:",
        schCatAll: "എല്ലാ വിഭാഗങ്ങളും",
        schCatEdu: "വിദ്യാഭ്യാസം",
        schCatHealth: "ആരോഗ്യ സംരക്ഷണം",
        schCatAgri: "കൃഷി",
        schCatWomen: "വനിതാ ക്ഷേമം",
        schCatSenior: "മുതിർന്ന പൗരന്മാർ",
        schCatEmp: "തൊഴിൽ",
        schCatHousing: "ഭവന നിർമ്മാണം",
        schCatChild: "ശിശുക്ഷേമം",
        schChipAll: "എല്ലാം",
        schChipEdu: "വിദ്യാഭ്യാസം",
        schChipHealth: "ആരോഗ്യം",
        schChipAgri: "കൃഷി",
        schChipWomen: "വനിതകൾ",
        schChipJobs: "ജോലികൾ",
        schResultsCount: "പദ്ധതികൾ കാണിക്കുന്നു",
        schModalEligTitle: "യോഗ്യതാ മാനദണ്ഡം",
        schModalBtn: "ഔദ്യോഗിക സൈറ്റ് സന്ദർശിക്കുക",
        schFooter: "© 2026 JAN-ASSIST. ഭാരതത്തിലെ ജനങ്ങൾക്കായി നിർമ്മിച്ചത്.",

        // Shared dynamic text (cards, details, copy)
        cardTopMatch: "മികച്ച പൊരുത്തം",
        cardEligible: "യോഗ്യൻ",
        cardEligMatch: "യോഗ്യതാ പൊരുത്തം",
        cardOfficialSite: "ഔദ്യോഗിക സൈറ്റ്",
        cardVisitSite: "സൈറ്റ് സന്ദർശിക്കുക",
        cardViewDetails: "വിശദാംശങ്ങൾ കാണുക",
        cardEligibilityLabel: "യോഗ്യത:",
        cardNoSchemesFound: "പദ്ധതികളൊന്നും കണ്ടെത്തിയില്ല",
        cardNoSchemesSub: "നിങ്ങളുടെ തിരച്ചിൽ പദങ്ങളോ ഫിൽട്ടർ മാനദണ്ഡങ്ങളോ മാറ്റാൻ ശ്രമിക്കുക.",
        cardShowingSchemes: "Showing <span>{count}</span> scheme{plural}"
    },
    kn: {
        // Navbar
        navHome: "ಮುಖಪುಟ",
        navAbout: "ನಮ್ಮ ಬಗ್ಗೆ",
        navEligibility: "ಅರ್ಹತೆ ಪರೀಕ್ಷಿಸಿ",
        navSchemes: "ಯೋಜನೆಗಳು",
        getStarted: "ಪ್ರಾರಂಭಿಸಿ",

        // Index page
        badge: "⭐ 12 ಲಕ್ಷಕ್ಕೂ ಹೆಚ್ಚು ನಾಗರಿಕರ ನಂಬಿಕೆ",
        title: '<span class="white-text">ಸರ್ಕಾರಿ ಬೆಂಬಲ,</span><br><span class="gradient-text">ಸರಳೀಕರಿಸಲಾಗಿದೆ</span>',
        sub: "ಕೇವಲ 2 ನಿಮಿಷಗಳಲ್ಲಿ 350+ ಕೇಂದ್ರ ಮತ್ತು ರಾಜ್ಯ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳಿಗೆ ನಿಮ್ಮ ಅರ್ಹತೆಯನ್ನು ಪರೀಕ್ಷಿಸಿ. ಉಚಿತ, ತ್ವರಿತ ಮತ್ತು ಸಂಪೂರ್ಣವಾಗಿ ಸುರಕ್ಷಿತ.",
        search: "ಹುಡುಕಿ",
        stat1: "ಲಭ್ಯವಿರುವ ಯೋಜನೆಗಳು",
        stat2: "ಸಹಾಯ ಪಡೆದ ನಾಗರಿಕರು",
        stat3: "ಒಳಗೊಂಡಿರುವ ರಾಜ್ಯಗಳು",
        categoryTitle: "ವರ್ಗದ ಮೂಲಕ ಬ್ರೌಸ್ ಮಾಡಿ",
        categorySub: "ವಿವಿಧ ಸರ್ಕಾರಿ ಇಲಾಖೆಗಳಲ್ಲಿ ನಿಮ್ಮ ಅಗತ್ಯಗಳಿಗೆ ಸರಿಹೊಂದುವ ಯೋಜನೆಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ",
        cat1: "ಶಿಕ್ಷಣ",
        cat2: "ಕೃಷಿ",
        cat3: "ಮಹಿಳಾ ಸಬಲೀಕರಣ",
        cat4: "ಹಿರಿಯ ನಾಗರಿಕರು",
        cat5: "ಆರೋಗ್ಯ ರಕ್ಷಣೆ",
        cat6: "ವಸತಿ",
        cat7: "ಮಕ್ಕಳ ಕಲ್ಯಾಣ",
        cat8: "ಉದ್ಯೋಗ",
        cat1_desc: "45 ಯೋಜನೆಗಳು",
        cat2_desc: "38 ಯೋಜನೆಗಳು",
        cat3_desc: "32 ಯೋಜನೆಗಳು",
        cat4_desc: "28 ಯೋಜನೆಗಳು",
        cat5_desc: "40 ಯೋಜನೆಗಳು",
        cat6_desc: "25 ಯೋಜನೆಗಳು",
        cat7_desc: "20 ಯೋಜನೆಗಳು",
        cat8_desc: "35 ಯೋಜನೆಗಳು",

        // About page
        aboutStory: "ನಮ್ಮ ಕಥೆ",
        aboutTitle: 'ಜನ-ಅಸಿಸ್ಟ್<br><span class="grad-text">ಬಗ್ಗೆ</span>',
        aboutDesc: "ಭಾರತದ ಅತ್ಯಂತ ವಿಶ್ವಾಸಾರ್ಹ ಸರ್ಕಾರಿ ಯೋಜನೆಯ ಅರ್ಹತಾ ವೇದಿಕೆ — 12 ಲಕ್ಷಕ್ಕೂ ಹೆಚ್ಚು ನಾಗರಿಕರು ತಮಗೆ ನಿಜವಾಗಿಯೂ ಅರ್ಹವಿರುವ ಕಲ್ಯಾಣ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಅನ್ವೇಷಿಸಲು, ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಮತ್ತು ಪ್ರವೇಶಿಸಲು ಸಬಲೀಕರಣಗೊಳಿಸುತ್ತದೆ.",
        aboutCheck: "ಅರ್ಹತೆ ಪರೀಕ್ಷಿಸಿ",
        aboutBrowse: "ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
        aboutScroll: "ಅನ್ವೇಷಿಸಲು ಸ್ಕ್ರಾಲ್ ಮಾಡಿ",
        aboutStat1: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
        aboutStat2: "ಬೆಂಬಲಿತ ನಾಗರಿಕರು",
        aboutStat3: "ಒಳಗೊಂಡಿರುವ ರಾಜ್ಯಗಳು",
        aboutStat4: "ಸುರಕ್ಷಿತ ವೇದಿಕೆ",
        aboutOffer: "ನಾವು ಏನು ನೀಡುತ್ತೇವೆ",
        aboutOfferTitle: 'ನಿಮಗಾಗಿಯೇ <span class="grad-text">ರೂಪಿಸಲಾಗಿದೆ</span>',
        aboutOfferSub: "ಪ್ರತಿ ವೈಶಿಷ್ಟ್ಯವನ್ನು ಘರ್ಷಣೆಯನ್ನು ತೆಗೆದುಹಾಕಲು ಮತ್ತು ಸರಿಯಾದ ಮಾಹಿತಿಯನ್ನು ತಕ್ಷಣವೇ ನಿಮ್ಮ ಕೈಗೆ ತಲುಪಿಸಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.",
        aboutPurposeTitle: "ನಮ್ಮ ಉದ್ದೇಶ",
        aboutPurposeBody: "ಜನ-ಅಸಿಸ್ಟ್ ನಾಗರಿಕರು ಮತ್ತು ಸರ್ಕಾರಿ ಕಲ್ಯಾಣ ಕಾರ್ಯಕ್ರಮಗಳ ನಡುವಿನ ಅಂತರವನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ. ಲಕ್ಷಾಂತರ ಅರ್ಹ ನಾಗರಿಕರು ತಮಗೆ ಸಿಗಬೇಕಾದ ಪ್ರಯೋಜನಗಳ ಬಗ್ಗೆ ತಿಳಿದಿಲ್ಲ — ಅದನ್ನು ಬದಲಾಯಿಸಲು ನಾವು ಅಸ್ತಿತ್ವದಲ್ಲಿದ್ದೇವೆ. ನಮ್ಮ ವೇದಿಕೆಯು ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಪ್ರೊಫೈಲ್ ಆಧರಿಸಿ ಅನ್ವೇಷಣೆಯನ್ನು ಸರಳಗೊಳಿಸುತ್ತದೆ.",
        aboutPurposeTag: "ಮುಖ್ಯ ಉದ್ದೇಶ",
        aboutMissionTitle: "ನಮ್ಮ ಧ್ಯೇಯ",
        aboutMissionBody: "ಶಿಕ್ಷಣ ಮಟ್ಟ, ಭಾಷೆ ಅಥವಾ ಸ್ಥಳವನ್ನು ಲೆಕ್ಕಿಸದೆ ಪ್ರತಿಯೊಬ್ಬ ಭಾರತೀಯ ನಾಗರಿಕನಿಗೆ ಸರ್ಕಾರಿ ಯೋಜನೆಯ ಅನ್ವೇಷಣೆಯನ್ನು ಶ್ರಮರಹಿತವಾಗಿಸುವುದು. ಕಲ್ಯಾಣಕ್ಕಾಗಿ ಮೀಸಲಿಟ್ಟ ಪ್ರತಿಯೊಂದು ರೂಪಾಯಿಯೂ ಅತ್ಯಂತ ಅಗತ್ಯವಿರುವವರನ್ನು ತಲುಪಬೇಕು ಎಂದು ನಾವು ನಂಬುತ್ತೇವೆ.",
        aboutMissionTag: "ಧ್ಯೇಯ ಆಧಾರಿತ",
        aboutBenefitsTitle: "ಪ್ರಮುಖ ಪ್ರಯೋಜನಗಳು",
        aboutBenefitsBody: "ಮನೆಯಿಂದಲೇ ಅರ್ಹತೆಯನ್ನು ಪರೀಕ್ಷಿಸಿ — ಯಾವುದೇ ಕ್ಯೂ ಇಲ್ಲ, ಯಾವುದೇ ಪೇಪರ್‌ವರ್ಕ್ ಇಲ್ಲ, ಯಾವುದೇ ಗೊಂದಲವಿಲ್ಲ. ನಮ್ಮ ತ್ವರಿತ ಮ್ಯಾಚಿಂಗ್ ಎಂಜಿನ್ ನಿಮ್ಮ ವಯಸ್ಸು, ಆದಾಯ, ಉದ್ಯೋಗ, ರಾಜ್ಯ ಮತ್ತು ವರ್ಗಕ್ಕೆ ಅತ್ಯಂತ ಸೂಕ್ತವಾದ ಯೋಜನೆಗಳನ್ನು ಪ್ರದರ್ಶಿಸಲು ಅಧಿಕೃತ ಮಾನದಂಡಗಳನ್ನು ಬಳಸುತ್ತದೆ.",
        aboutBenefitsTag: "ಯಾವಾಗಲೂ ಉಚಿತ",
        aboutTransTitle: "ಸಂಪೂರ್ಣ ಪಾರದರ್ಶಕತೆ",
        aboutTransBody: "ನಾವು ಪ್ರತಿ ಯೋಜನೆಗೆ ಸ್ಪಷ್ಟವಾದ, ಸಂಪೂರ್ಣ ಅರ್ಹತಾ ಮಾನದಂಡಗಳನ್ನು ಪ್ರದರ್ಶಿಸುತ್ತೇವೆ — ನೇರವಾಗಿ ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಮೂಲಗಳಿಂದ. ಯಾವುದೇ ಗುಪ್ತ ಹಂತಗಳಿಲ್ಲ. ಪಾವತಿ ಗೋಡೆಗಳಿಲ್ಲ. ತಪ್ಪುದಾರಿಗೆಳೆಯುವ ಸಾರಾಂಶಗಳಿಲ್ಲ. ನೀವು ನೋಡುವುದು ನಿಖರವಾಗಿ ಅಗತ್ಯವಿರುವಂತದ್ದಾಗಿದೆ.",
        aboutTransTag: "ಮುಕ್ತ ಡೇಟಾ",
        aboutAccessTitle: "ಪ್ರವೇಶಿಸುವಿಕೆಗೆ ಆದ್ಯತೆ",
        aboutAccessBody: "ಇಂಗ್ಲಿಷ್, ತಮಿಳು, ಹಿಂದಿ, ಮಲಯಾಳಂ, ತೆಲುಗು ಮತ್ತು ಕನ್ನಡ ಸೇರಿದಂತೆ 6 ಪ್ರಾದೇಶಿಕ ಭಾಷೆಗಳಲ್ಲಿ ಲಭ್ಯವಿದೆ. ಯಾವುದೇ ಸಾಧನ, ಯಾವುದೇ ಪರದೆಯ ಗಾತ್ರ ಮತ್ತು ಗ್ರಾಮೀಣ ಭಾರತದಾದ್ಯಂತ ನಿಧಾನಗತಿಯ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕಗಳಲ್ಲಿಯೂ ಕಾರ್ಯನಿರ್ವಹಿಸಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.",
        aboutAccessTag: "6 ಭಾಷೆಗಳು",
        aboutGovtTitle: "ಯೋಜನಾ ಬೆಂಬಲ",
        aboutGovtBody: "ಪಿಎಂ-ಕಿಸಾನ್‌ನಿಂದ ಬೇಟಿ ಬಚಾವೊ ಬೇಟಿ ಪಢಾವೊವರೆಗೆ — ನಾವು ಶಿಕ್ಷಣ, ಕೃಷಿ, ಆರೋಗ್ಯ ರಕ್ಷಣೆ, ವಸತಿ, ಮಹಿಳಾ ಕಲ್ಯಾಣ ಮತ್ತು ಹೆಚ್ಚಿನವುಗಳಲ್ಲಿ 350+ ಕೇಂದ್ರ ಮತ್ತು ರಾಜ್ಯ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಒಳಗೊಂಡಿದೆ. ಪ್ರತಿ ಯೋಜನೆಯೂ ತನ್ನ ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್‌ಗೆ ಲಿಂಕ್ ಮಾಡುತ್ತದೆ.",
        aboutGovtTag: "350+ ಯೋಜನೆಗಳು",
        aboutQuote: "ಭಾರತದ ಪ್ರತಿಯೊಬ್ಬ ನಾಗರಿಕನಿಗೂ ತನಗೆ ಅರ್ಹವಿರುವ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳ ಬಗ್ಗೆ ತಿಳಿಯಲು ಮತ್ತು ಪ್ರವೇಶಿಸಲು ಅರ್ಹತೆ ಇದೆ. ಜನ-ಅಸಿಸ್ಟ್ ಇದನ್ನು ನಿಜ ಮಾಡುತ್ತದೆ.",
        aboutCite: "— ಜನ-ಅಸಿಸ್ಟ್ ತಂಡ",
        aboutValuesTag: "ನಮ್ಮ ಮೌಲ್ಯಗಳು",
        aboutValuesTitle: "ನಾವು ಯಾವುದಕ್ಕಾಗಿ ಬದ್ಧರಾಗಿದ್ದೇವೆ",
        aboutV1: "ನಾಗರಿಕ ಮೊದಲ ಆದ್ಯತೆ",
        aboutV2: "ಡೇಟಾ ಗೌಪ್ಯತೆ",
        aboutV3: "ವೇಗ ಮತ್ತು ನಿಖರತೆ",
        aboutV4: "ಉಚಿತ ಮತ್ತು ಮುಕ್ತ",
        aboutV5: "ಬಹುಭಾಷಾ",
        aboutV6: "ಸಮಗ್ರ ವಿನ್ಯಾಸ",
        aboutV7: "100% ಸುರಕ್ಷಿತ",
        aboutV8: "ಸರ್ಕಾರದಿಂದ ಪರಿಶೀಲಿಸಲ್ಪಟ್ಟಿದೆ",
        aboutV9: "ಮೊಬೈಲ್ ಸ್ನೇಹಿ",
        aboutV10: "ಯಾವಾಗಲೂ ನವೀಕರಿಸಲಾಗುತ್ತದೆ",
        aboutCtaTitle: "ಪ್ರಾರಂಭಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
        aboutCtaDesc: "ಈಗಾಗಲೇ ತಮ್ಮ ಸರ್ಕಾರಿ ಪ್ರಯೋಜನಗಳನ್ನು ಕಂಡುಕೊಂಡಿರುವ 12 ಲಕ್ಷಕ್ಕೂ ಹೆಚ್ಚು ನಾಗರಿಕರೊಂದಿಗೆ ಸೇರಿ. ಇದಕ್ಕೆ 2 ನಿಮಿಷಗಳಿಗಿಂತ ಕಡಿಮೆ ಸಮಯ ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ — ಸಂಪೂರ್ಣವಾಗಿ ಉಚಿತ.",
        aboutCtaBtn: "ನನ್ನ ಅರ್ಹತೆಯನ್ನು ಪರೀಕ್ಷಿಸಿ",
        aboutFooter: "© 2026 JAN-ASSIST · ಸರ್ಕಾರಿ ಬೆಂಬಲ, ಸರಳವಾಗಿ",

        // Eligibility page
        eligEyebrow: "ನಾಗರಿಕ ಸೇವೆಗಳ ಪೋರ್ಟಲ್",
        eligTitle: "ನಿಮ್ಮ ಅರ್ಹತೆಯನ್ನು ಪರೀಕ್ಷಿಸಿ",
        eligSub: "ಕೆಲವು ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ ಮತ್ತು ನೀವು ಅರ್ಹತೆ ಪಡೆಯುವ ಪ್ರತಿ ಸರ್ಕಾರಿ ಕಲ್ಯಾಣ ಯೋಜನೆಯೊಂದಿಗೆ ನಮ್ಮ ಸಿಸ್ಟಮ್ ನಿಮ್ಮನ್ನು ತಕ್ಷಣವೇ ಹೊಂದಿಸುತ್ತದೆ.",
        eligStep1: "ಪ್ರೊಫೈಲ್",
        eligStep2: "ವಿವರಗಳು",
        eligStep3: "ಫಲಿತಾಂಶಗಳು",
        eligSecA: "ವೈಯಕ್ತಿಕ ಪ್ರೊಫೈಲ್",
        eligSecB: "ಆರ್ಥಿಕ ಮತ್ತು ಸಾಮಾಜಿಕ ವಿವರಗಳು",
        eligName: "ಪೂರ್ಣ ಹೆಸರು",
        eligNamePlaceholder: "ಉದಾಹರಣೆಗೆ: ಗೂಗನ್",
        eligNameInvalid: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ (ಕನಿಷ್ಠ 3 ಅಕ್ಷರಗಳು)",
        eligAge: "ವಯಸ್ಸು",
        eligAgePlaceholder: "18-100",
        eligAgeInvalid: "ಮಾನ್ಯವಾದ ವಯಸ್ಸನ್ನು ನಮೂದಿಸಿ (1-120)",
        eligGender: "ಲಿಂಗ",
        eligGenderSelect: "ಆರಿಸಿ",
        eligGenderMale: "ಪುರುಷ",
        eligGenderFemale: "ಮಹಿಳೆ",
        eligGenderOther: "ಇತರ",
        eligGenderInvalid: "ದಯವಿಟ್ಟು ಲಿಂಗವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
        eligState: "ರಾಜ್ಯ / ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶ",
        eligStateSelect: "ನಿಮ್ಮ ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
        eligStateInvalid: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
        eligOccupation: "ಉದ್ಯೋಗ",
        eligOccSelect: "ಉದ್ಯೋಗ ಆಯ್ಕೆ ಮಾಡಿ",
        eligOccFarmer: "ರೈತ / ಕೃಷಿ ಕಾರ್ಮಿಕ",
        eligOccSenior: "ಹಿರಿಯ ನಾಗರಿಕ",
        eligOccStudent: "ವಿದ್ಯಾರ್ಥಿ",
        eligOccUnemployed: "ನಿರುದ್ಯೋಗಿ",
        eligOccHomemaker: "ಗೃಹಿಣಿ",
        eligOccRetired: "ನಿವೃತ್ತ",
        eligOccInvalid: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಉದ್ಯೋಗವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
        eligIncome: "ವಾರ್ಷಿಕ ಕೌಟುಂಬಿಕ ಆದಾಯ",
        eligIncomeSub: "ವಾರ್ಷಿಕ ಕೌಟುಂಬಿಕ ಆದಾಯ",
        eligCategory: "ಸಾಮಾಜಿಕ ವರ್ಗ",
        eligCatSelect: "ವರ್ಗವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
        eligCatGeneral: "ಸಾಮಾನ್ಯ",
        eligCatObc: "OBC (ಇತರ ಹಿಂದುಳಿದ ವರ್ಗಗಳು)",
        eligCatSc: "SC (ಪರಿಶಿಷ್ಟ ಜಾತಿ)",
        eligCatSt: "ST (ಪರಿಶಿಷ್ಟ ಪಂಗಡ)",
        eligCatEws: "EWS (ಆರ್ಥಿಕವಾಗಿ ದುರ್ಬಲ ವರ್ಗ)",
        eligCatMinority: "ಅಲ್ಪಸಂಖ್ಯಾತ ಸಮುದಾಯ",
        eligCatInvalid: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ವರ್ಗವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
        eligContact: "ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
        eligContactPlaceholder: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
        eligDataLoc: "ನಿಮ್ಮ ಡೇಟಾವನ್ನು ಸ್ಥಳೀಯವಾಗಿ ಪ್ರಕ್ರಿಯಗೊಳಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಎಂದಿಗೂ ಸಂಗ್ರಹಿಸಲಾಗುವುದಿಲ್ಲ.",
        eligScanBtn: "ಅರ್ಹತೆಯನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
        eligResTitle: "ಅರ್ಹತೆಯ ಫಲಿತಾಂಶಗಳು",
        eligResMeta: "ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
        eligStatMatched: "ಹೊಂದಿಕೆಯಾದ ಯೋಜನೆಗಳು",
        eligStatTopScore: "ಉನ್ನತ ಹೊಂದಾಣಿಕೆ",
        eligStatBenefit: "ಸಂಭಾವ್ಯ ಪ್ರಯೋಜನ",
        eligSearchPlaceholder: "ಯೋಜನೆಯ ಹೆಸರು ಅಥವಾ ಸಚಿವಾಲಯದ ಮೂಲಕ ಫಿಲ್ಟರ್ ಮಾಡಿ…",
        eligResNoMatch: "ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಯಾವುದೇ ಯೋಜನೆಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ. ವಿಭಿನ್ನ ಕೀವರ್ಡ್‌ಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ.",
        eligRecheck: "ಹೊಸ ಪ್ರೊಫೈಲ್‌ನೊಂದಿಗೆ ಮರು-ಪರೀಕ್ಷಿಸಿ",
        eligFooter: "© 2026 JAN-ASSIST · ಸರ್ಕಾರಿ ಬೆಂಬಲ, ಸರಳವಾಗಿ",

        // Schemes page
        schBadge: "ನಿಮ್ಮ ಪ್ರಯೋಜನಗಳನ್ನು ತಕ್ಷಣವೇ ಅನ್ವೇಷಿಸಿ",
        schTitle: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು<br><span class="gradient-text">ಅನ್ವೇಷಿಸಿ</span>',
        schSub: "ಸರ್ಕಾರಿ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳ ಭಾರತದ ಅತ್ಯಂತ ಸಮಗ್ರ ಡೇಟಾಬೇಸ್ ಅನ್ನು ನ್ಯಾವಿಗೇಟ್ ಮಾಡಿ. ಹುಡುಕಿ, ಫಿಲ್ಟರ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಅಗತ್ಯಗಳಿಗೆ ಸೂಕ್ತವಾದ ಯೋಜನೆಯನ್ನು ಕಂಡುಕೊಳ್ಳಿ — ಎಲ್ಲವೂ ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ.",
        schStatTotal: "ಒಟ್ಟು ಯೋಜನೆಗಳು",
        schStatCat: "ವರ್ಗಗಳು",
        schStatFree: "ಉಚಿತ ಪ್ರವೇಶ",
        schSearchBtn: "ಹುಡುಕಿ",
        schSearchPlaceholder: "ಯೋಜನೆಯ ಹೆಸರು, ವರ್ಗ ಅಥವಾ ವಿವರಣೆಯ ಮೂಲಕ ಹುಡುಕಿ...",
        schFilters: "ಫಿಲ್ಟರ್‌ಗಳು:",
        schCatAll: "ಎಲ್ಲಾ ವರ್ಗಗಳು",
        schCatEdu: "ಶಿಕ್ಷಣ",
        schCatHealth: "ಆರೋಗ್ಯ ರಕ್ಷಣೆ",
        schCatAgri: "ಕೃಷಿ",
        schCatWomen: "ಮಹಿಳಾ ಕಲ್ಯಾಣ",
        schCatSenior: "ಹಿರಿಯ ನಾಗರಿಕರು",
        schCatEmp: "ಉದ್ಯೋಗ",
        schCatHousing: "ವಸತಿ",
        schCatChild: "ಮಕ್ಕಳ ಕಲ್ಯಾಣ",
        schChipAll: "ಎಲ್ಲಾ",
        schChipEdu: "ಶಿಕ್ಷಣ",
        schChipHealth: "ಆರೋಗ್ಯ",
        schChipAgri: "ಕೃಷಿ",
        schChipWomen: "ಮಹಿಳೆಯರು",
        schChipJobs: "ಉದ್ಯೋಗಗಳು",
        schResultsCount: "ಯೋಜನೆಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ",
        schModalEligTitle: "ಅರ್ಹತೆಯ ಮಾನದಂಡ",
        schModalBtn: "ಅಧಿಕೃತ ಸೈಟ್‌ಗೆ ಭೇಟಿ ನೀಡಿ",
        schFooter: "© 2026 JAN-ASSIST. ಭಾರತದ ಜನರಿಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.",

        // Shared dynamic text (cards, details, copy)
        cardTopMatch: "ಉನ್ನತ ಹೊಂದಾಣಿಕೆ",
        cardEligible: "ಅರ್ಹರು",
        cardEligMatch: "ಅರ್ಹತೆ ಹೊಂದಾಣಿಕೆ",
        cardOfficialSite: "ಅಧಿಕೃತ ಸೈಟ್",
        cardVisitSite: "ಸೈಟ್‌ಗೆ ಭೇಟಿ ನೀಡಿ",
        cardViewDetails: "ವಿವರಗಳನ್ನು ನೋಡಿ",
        cardEligibilityLabel: "ಅರ್ಹತೆ:",
        cardNoSchemesFound: "ಯಾವುದೇ ಯೋಜನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
        cardNoSchemesSub: "ನಿಮ್ಮ ಹುಡುಕಾಟದ ಪದಗಳನ್ನು ಅಥವಾ ಫಿಲ್ಟರ್ ಮಾನದಂಡಗಳನ್ನು ಹೊಂದಿಸಲು ಪ್ರಯತ್ನಿಸಿ.",
        cardShowingSchemes: "Showing <span>${count}</span> scheme${plural}"
    }
};

// Global translation lookup helper for dynamically rendered strings
window.getTxt = function(key, replacements = {}) {
    const lang = localStorage.getItem('preferredLanguage') || 'en';
    const t = translations[lang] || translations['en'];
    let str = t[key] || translations['en'][key] || key;
    
    // Process string replacements
    for (const [k, v] of Object.entries(replacements)) {
        str = str.replace(`{${k}}`, v);
    }
    return str;
};

// Main DOM translation engine
window.translatePage = function(lang) {
    localStorage.setItem('preferredLanguage', lang);
    const t = translations[lang] || translations['en'];

    // 1. Update all dropdown select elements to display the correct selection
    const switchers = document.querySelectorAll('#languageSwitcher');
    switchers.forEach(sw => {
        if (sw.value !== lang) {
            sw.value = lang;
        }
    });

    // 2. Walk elements with data-i18n attribute and update content/placeholder
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const text = t[key] || translations['en'][key];
        if (!text) return;

        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
            el.placeholder = text;
        } else if (el.tagName === 'OPTION') {
            el.textContent = text;
        } else {
            // Render text as HTML if it contains tags, otherwise textContent
            if (text.includes('<') && text.includes('>')) {
                el.innerHTML = text;
            } else {
                // If the element has kids (like an icon <i>), preserve them and update trailing text
                const icon = el.querySelector('i');
                if (icon) {
                    // Empty the non-icon nodes and append new text
                    el.innerHTML = '';
                    el.appendChild(icon);
                    el.appendChild(document.createTextNode(' ' + text));
                } else {
                    el.textContent = text;
                }
            }
        }
    });

    // 3. Update document title language if page-specific title defined
    // We keep existing titles for SEO, but can translate details if desired.

    // 4. Force run any page-specific dynamic translation update hooks
    if (window.onLanguageChanged) {
        window.onLanguageChanged(lang);
    }
};

// Handle elements toggle and initialization on DOMContentLoaded
document.addEventListener('DOMContentLoaded', () => {
    // A. Hamburger menu wireup
    const mobileMenuBtn = document.getElementById('mobileMenuBtn');
    const navLinks = document.getElementById('navLinksMenu') || document.querySelector('.nav-links');
    if (mobileMenuBtn && navLinks) {
        mobileMenuBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            navLinks.classList.toggle('mobile-open');
        });
        // Close menu when clicking outside
        document.addEventListener('click', (e) => {
            if (navLinks.classList.contains('mobile-open') && !navLinks.contains(e.target) && e.target !== mobileMenuBtn) {
                navLinks.classList.remove('mobile-open');
            }
        });
    }

    // B. Setup language select switcher event listener
    document.addEventListener('change', (e) => {
        if (e.target && e.target.id === 'languageSwitcher') {
            const newLang = e.target.value;
            window.translatePage(newLang);
        }
    });

    // C. Initialize to preserved or default language
    const savedLang = localStorage.getItem('preferredLanguage') || 'en';
    window.translatePage(savedLang);
});
